### ISSUE TITLE
Fix import schemas not working

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1004]
**Background**
Users report that the https://dlthub.com/docs/walkthroughs/adjust-a-schema does not work anymore. We should reproduce the workflow and make sure it is OK. What is reported:
- schemas in import folder are overwritten on each run
- when full refresh is used, schemas are overwritten with some weird names

**Comment by sh-rp** [comment]
Both reports do not seem to be correct (i will follow up with the reporter though), what does seem to be the case though is, that the hints and columns added in the import schema are not respected at all.

**Comment by sh-rp** [comment]
When full_refresh is false, the import schema gets overwritten.
