### ISSUE TITLE
Cannot change the schema contract

### ISSUE THREAD

**Issue by khoadaniel** [dlt-hub/dlt#1011]
### dlt version

0.4.5

### Describe the problem

The schema contract cannot be changed after its creation.

### Expected behavior

Schema contracts should allow changes.

### How to reproduce:
- Step 1: Sync sample data (below) with `"columns": "freeze"` :arrow_right: all good.
- Step 2: Sync data with an extra column :arrow_right: dlt threw `DataValidationError`, which is the correct behavior.
- Step 3: Changed schema contract to `"columns": "evolve"` and then sync again :arrow_right: dlt still threw `DataValidationError` regarding the extra column.

```
import dlt

SCHEMA_CONTRACT = {"tables": "evolve",
                   "columns": "freeze", # then changed to "evolve"
                   "data_type": "freeze"}

@dlt.resource(write_disposition="merge", table_name="test_table", primary_key="name", schema_contract=SCHEMA_CONTRACT)
def my_resource():
    test_data = [{"name": "John", "age": 30, "city": "New York"},
                 {"name": "Alice", "age": 25, "city": "Los Angeles"},
                 {"name": "Bob", "age": 40, "city": "Chicago"}]
    yield test_data

load_info = dlt.pipeline(
    pipeline_name="test_pipeline", destination="postgres", dataset_name="dlt_test_merge").run(my_resource())

print(load_info)
```

### DataValidationError
```
<class 'dlt.normalize.exceptions.NormalizeJobFailed'>
Job for test_table.c8fa484cb3.jsonl failed terminally in load 1709029756.725476 with message In Schema: test Table: test_table Column: city . Contract on columns with mode freeze is violated. Trying to add column city to table test_table but columns are frozen..
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.10

### dlt data source

Just a sample source.

### dlt destination

Postgres

**Comment by sh-rp** [comment]
Hey @khoadaniel, thanks for reporting this. Your data is failing in the normalization stage, this means if you retry, then only the normalization will be retried and the contract settings in your resources will not be evaluated again. You have two possibilities if this happens:

1. Drop the pending load packages for this pipeline with dlt pipeline <pipeline name> drop-pending-packages, then the full pipeline will run anew including the extraction.
2. Modify the current schema directly to allow for extra columns. Right now this is not working properly but this pr will fix that: https://github.com/dlt-hub/dlt/pull/1012. After this is merged, you can directly modify the schema:
```
p = dlt.pipeline....
p.default_schema.tables["test_table"]["schema_contract"] = {"columns": "evolve"}
p.run(...)
```

**Comment by khoadaniel** [comment]
> Hey @khoadaniel, thanks for reporting this. Your data is failing in the normalization stage, this means if you retry, then only the normalization will be retried and the contract settings in your resources will not be evaluated again. You have two possibilities if this happens:
> 
> 1. Drop the pending load packages for this pipeline with dlt pipeline  drop-pending-packages, then the full pipeline will run anew including the extraction.
> 2. Modify the current schema directly to allow for extra columns. Right now this is not working properly but this pr will fix that: [clear normalized package in case it already existed #1012](https://github.com/dlt-hub/dlt/pull/1012). After this is merged, you can use the global override
> 
> ```
> p = dlt.pipeline....
> p.run(schema_contract={"columns": "evolve"})
> ```

Noted, thanks @sh-rp .
I usually brute force `rm rf ~/.dlt/pipelines` instead of using `drop-pending-packages` 😆
