### ISSUE TITLE
`make_hints` returns default `write_disposition` if no disposition is provided as input

### ISSUE THREAD

**Issue by jorritsandbrink** [dlt-hub/dlt#1031]
### dlt version

0.4.4

### Describe the problem

The `make_hints` function returns a `TResourceHints` object containing a value for `write_disposition` when `make_hints` was called without the `write_disposition` argument.

This is for example problematic when yielding hints in a resource:

![image](https://github.com/dlt-hub/dlt/assets/47451109/854d08e7-7bea-46d5-b1d8-bfd768813681)
![image](https://github.com/dlt-hub/dlt/assets/47451109/548577fa-4c75-41dd-a4b0-142d7e152183)
![image](https://github.com/dlt-hub/dlt/assets/47451109/f39dc4e4-8040-4551-b848-80fcf45dfb64)

### Expected behavior

`make_hints` only returns hints that were explicitly provided as input in the function's arguments, not using any default values.

### Steps to reproduce

```python
from dlt.extract.hints import make_hints

print(make_hints())
```

output:
`{'columns': {}, 'write_disposition': 'append'}`

### Operating system

Windows

### Runtime environment

Local

### Python version

3.8

**Comment by rudolfix** [comment]
`new_table()` adds default write disposition. we should get rid of it like we do with `table_format`. this will cause problem in `apply_hints` of resource.py and in decorator.py - they expect default write disposition to be created. so there we should pass it explicitly. some make_hints test would be cool
