### ISSUE TITLE
Schema import overwritten upon pipeline execution

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/dlt#1033]
### dlt version

0.4.5

### Describe the problem

The issue is based on a Slack chat. 
Slack chat --> [here](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1708641820106789)

After exporting the schema for an existing pipeline and making a minor amendment to the YAML file, user attempted to use this modified version through import_schema_path. However, upon running the pipeline, even in a new, empty database, the YAML in the import schema reverts to its original state, ignoring the modifications made. This behavior contradicts the expected functionality of the import schema, acting as a scaffold for the pipeline's schema.

### Expected behavior

The user expected the modified schema specified in import_schema_path to be used throughout the pipeline execution, with the pipeline's output schema reflecting only new inferences or modifications made during the run. The import schema should remain as amended by the user, facilitating controlled schema evolution.

### Steps to reproduce

1. Export the existing pipeline schema using export_schema_path.1
2. Amend the exported YAML file to introduce a minor change.
3. Set the amended YAML file as the import schema using import_schema_path.
4. Run the pipeline and observe that the import schema reverts to its original state, disregarding the user-made modifications.

### Operating system

Linux

### Runtime environment

Local

### Python version

3.11

### dlt destination

MotherDuck

**Comment by dttung-sumup** [comment]
Hi @dat-a-man , we encounter similar problem as you. May I know how did you manage to resolve it ?
