### ISSUE TITLE
Cache OAuth data when connecting to Snowflake

### ISSUE THREAD

**Issue by b-per** [dlt-hub/dlt#1035]
### Feature description

I set up Snowflake as a destination of a pipeline, using the OAuth + `externalbrowser` set up, but to load 4 tables, I am prompted ~15 times to log in via Okta.

It would be great if we could cache the token to reuse it for the next connections in the same pipeline.

It seems that there might be an issue also when having a source with multiple resources that we want to load to Snowflake with `externalbrowser` auth.

The pipeline process sometimes stop in the middle and I need to click on the different browser links to get it going. Some of those links return a `localhost not found` in the browser but when I "find" the URL that is pausing the process and I SSO via it, the process continues.

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Connection to Snowflake using OAuth and the `externalbrowser` authentication type

### Proposed solution

Caching the authentication after the first prompt to sign in using SSO.

**Comment by rudolfix** [comment]
it looks like it is some kind of server option:
https://docs.snowflake.com/en/user-guide/security-mfa#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional

so if enabled, the client should start caching. @b-per does it help in any way?

maybe we miss some additional parameter to `external`? with actual cookie so you are able to run everything headless without going to the browser. I'll do more research tomorrow

**Comment by b-per** [comment]
What you are linking is actually about caching MFA, which is different from OAuth.

I generally connect to the same Snowflake Data Warehouse using dbt with OAuth + `externalbrowser` and I am only prompted once to go though the SSO flow, despite the fact that many queries are run.

Reading [this doc](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional) it seems that we can get OAuth creds caching by installing the optional package `secure-local-storage`  like in `pip install "snowflake-connector-python[secure-local-storage]"`

**Comment by b-per** [comment]
I just added `"secure-local-storage"` locally and can confirm that it only requests once to connect to the browser. No code change required.

**Comment by rudolfix** [comment]
cool! they mentioned the same "secure storage" in MFA doc.
@b-per I do not understand how this is supposed to work in production? if the browser is involved, there's no headless run. there must be a way to generate such cookie in advance and somehow pass it to the snowflake connector. tell me if that is a problem. we can dig deeper

@VioletM looks like we should add this to troubleshooting section at some point

**Comment by b-per** [comment]
This use case is not for production but only for local runs as it requires some manual intervention as you mentioned. 

But it is a pretty good improvement in quality of life for the local developer.
