### ISSUE TITLE
CI fails on forks: deploy docs workflow run

### ISSUE THREAD

**Issue by willi-mueller** [dlt-hub/dlt#1067]
### dlt version

0.4.6

### Describe the problem

In my fork of this dlt repository I have now a daily workflow run which has been failing since at least the commit 9410bc4.

I just manually tried it with the latest commit 3761335e6

Error message:
```
Run curl  -X POST
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Error: Process completed with exit code 2.
```

Link to failed run: https://github.com/willi-mueller/dlt/actions/runs/8197767018/job/22420227197

### Expected behavior

Do not run the workflow `deploy docs` on forks. I have no intention to build and deploy documentation.

### Steps to reproduce

1. fork the dlt repo
1. wait until 2am UTC for CRON to trigger or manually execute the .github/workflows/deploy_docs.yml

### Operating system

Linux

### Runtime environment

Other

### Python version

3.11

**Comment by sh-rp** [comment]
hey @willi-mueller, this short pr should take care of it, thanks for reporting :) 
https://github.com/dlt-hub/dlt/pull/1147/files
