### ISSUE TITLE
Clarification and Documentation on Lookback Windows in Incremental Loads

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/dlt#1068]
### Feature description

Documentation and examples are needed to clarify the behavior of incremental resources when implementing lookback windows. Currently, records older than incremental.last_value are dropped, which can be counterintuitive, especially when write_disposition is set to merge. This behavior can be implemented using "last_value_func". To be documented in the incremental loading documentation.

Slack thread: [here](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1709196207045829)

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Developers implementing incremental loads with a requirement for lookback windows face challenges due to the absence of clear documentation on handling records older than the last value.

### Proposed solution

Update documentation to include specific examples of implementing lookback windows.

**Comment by rudolfix** [comment]
implementing lookback window is really tricky and we must do it 'directly" here: #lag
