### ISSUE TITLE
Performance Degradation with Incremental Pipeline Runs When Capturing load_info

### ISSUE THREAD

**Issue by dat-a-man** [dlt-hub/dlt#1069]
### Feature description

Slack thread: [here](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1709412446163619)

When capturing load_info data within the destination database, there is a significant performance drop in pipeline execution over time. Initially, the job runs at a normal pace (approx. 1.5 minutes) but gradually slows down to over 10 minutes after several hundred runs, potentially due to the creation of new tables with single records for each run, named in the format _load_info__metrics___[timestamp]_[id]. This issue persists even after the load_info_metrics__ tables are deleted, suggesting it may not be related to the database's handling of the tables.

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

The user is using dlt for sourcing data from REST APIs and capturing it in MotherDuck.

### Proposed solution

The issue with load_info.metrics is that it's structured inefficiently for dlt processing. It contains a list of dictionaries keyed by load IDs, which causes the database schema to expand unnecessarily with each pipeline execution. To address this, consider the following options before loading the load_info data:

1.  Remove the load ID key from the dictionary.
2.  Either pop the key before loading the load info. Or json dumps it. 
3. Encapsulate load_info within its own source, setting a maximum table nesting level to control schema expansion.

It is advised to revise the dlt's loading strategy for load_info to avoid using keys that are not deterministic, thereby enhancing performance and preventing schema bloating.

**Comment by sultaniman** [comment]
So this has been fixed in 0.4.6 https://github.com/dlt-hub/dlt/pull/1051

**Comment by sultaniman** [comment]
@dat-a-man I will drop a message w/ explanation about the fix.
