### ISSUE TITLE
For snowflake destination column names ended with _ replaced with x ending

### ISSUE THREAD

**Issue by VioletM** [dlt-hub/dlt#1074]
### dlt version

0.4.5

### Describe the problem

If I have Snowflake as a destination, and the column name is ended with an underscore, in Snowflake it will be replaced with x at the end.

Example,

```
ESTIMATED_KICK_OFF_MONTH_ -> ESTIMATED_KICK_OFF_MONTHX
HAS_LOGGED_INTO_TAKTILE_DECIDE_-> HAS_LOGGED_INTO_TAKTILE_DECIDEX
```

### Expected behavior

I expect column names to be the same in destination as in source

```
ESTIMATED_KICK_OFF_MONTH_ -> ESTIMATED_KICK_OFF_MONTH_
HAS_LOGGED_INTO_TAKTILE_DECIDE_-> HAS_LOGGED_INTO_TAKTILE_DECIDE_
```

### Steps to reproduce

For example,

```
import dlt


@dlt.resource
def some_data():
    for i in range(10):
        yield {"my_col_1_": i, "my_col_2_": i * 2}


pipeline = dlt.pipeline(destination="snowflake")
pipeline.run(some_data())
```
will generate table
<img width="964" alt="image" src="https://github.com/dlt-hub/dlt/assets/9139429/7c4d22ee-1c79-4a48-a8f8-15d0c87af0e0">

### Operating system

macOS

### Runtime environment

Local

### Python version

3.9

### dlt destination

Snowflake

**Comment by rudolfix** [comment]
from 0.5.x possible via setting up `sql_ci_v1` naming convention
