### ISSUE TITLE
example documentation task

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#1090]
Slack thread:
https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1709641456213189

Description:
User wanted some explaination regarding  docs or examples that use dlt with a BigQuery destination (and GCS staging), where the BigQuery and GCS clients are currently Dagster resources. Zaeem guided the user how to do this

to do:
Add example to the (future?) dagster deployment documentation page.

**Comment by rudolfix** [comment]
@adrianbr @dat-a-man can we close it?

**Comment by dat-a-man** [comment]
Yes, it can be closed.
