### ISSUE TITLE
Streamlit not working (dlt pipeline show) with custom pipelines_dir

### ISSUE THREAD

**Issue by sohooo** [dlt-hub/dlt#1098]
### dlt version

0.4.6

### Describe the problem

When changing the simple [tutorial from the docs](https://dlthub.com/docs/tutorial/load-data-from-an-api) to include setting `pipelines_dir`, Streamlit doesn't work anymore:

```bash
dlt pipeline --pipelines-dir ./pipelines github_issues show
```

Error in Browser:

> CannotRestorePipelineException: Pipeline with name github_issues in working directory /Users/sohooo/.dlt/pipelines could not be restored: the pipeline was not found in /Users/sohooo/.dlt/pipelines/github_issues.
`

### Expected behavior

Streamlit data preview should pick up the `--pipelines-dir` flag, just like the `info` call:

```bash
❯ dlt pipeline --pipelines-dir ./pipelines github_issues info
Found pipeline github_issues in ./pipelines
Synchronized state:
_state_version: 1
_state_engine_version: 4
default_schema_name: github_issues
dataset_name: github_data
pipeline_name: github_issues
schema_names: ['github_issues']
destination_type: dlt.destinations.duckdb
destination_name: duckdb
_version_hash: eSkmcf/dWqzw12abWvMWBpcRVPQw0el16Jpaq63MZIc=

Local state:
first_run: False
_last_extracted_at: 2024-03-16 19:33:26.035161+00:00
```

### Steps to reproduce

Tutorial code, with `pipelines_dir` arg:

```python
import os
import dlt
from dlt.sources.helpers import requests

url = "https://api.github.com/repos/dlt-hub/dlt/issues"

# make a request and check if successful
response = requests.get(url)
response.raise_for_status()

proj_path = os.path.dirname(__file__)
pipelines_path = os.path.join(proj_path, "pipelines")

pipeline = dlt.pipeline(
    pipeline_name="github_issues",
    pipelines_dir=pipelines_path,
    destination="duckdb",
    dataset_name="github_data",  # schema name
)

# the response contains a list of github issues
load_info = pipeline.run(response.json(), table_name="issues")
print(load_info)
```

Call:
```bash
dlt pipeline --pipelines-dir ./pipelines github_issues show
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

**Comment by rudolfix** [comment]
this makes sense! @sultaniman please make sure we handle this in the streamlit upgrade that we release this week

**Comment by sultaniman** [comment]
Will be fixed along with https://github.com/dlt-hub/dlt/pull/1060
