### ISSUE TITLE
Allow to specify field "encrypt" on mssql target

### ISSUE THREAD

**Issue by gbonazzoli** [dlt-hub/dlt#1169]
### Feature description

In order to connect to SQL Server Database I had to use in `.dlt/secrets.otml` the following escamotage:

```
[destination.mssql.credentials]
database = "DesmosColombiniTest" # please set me up!
password = "<mysuser>" # please set me up!
username = "<mypassword>;Encrypt=no" # please set me up!
host = "172.16.0.32" # please set me up!
port = 1433
connect_timeout = 15
encrypt = "no"
drivername = "ODBC Driver 18 for SQL Server"
```

As you can see the field=values `Encrypt=no` was inserted into the username field

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

Was a test of completeness

### Proposed solution

Insert a new field `.dlt/secrets.otml` in `[destination.mssql.credentials]`

Encrypt=yes|no

**Comment by rudolfix** [comment]
@gbonazzoli you can pass any additional parameters using SQLAlchemy like connection string, see here:
https://dlthub.com/docs/dlt-ecosystem/destinations/mssql

so
```
# keep it at the top of your toml file! before any section starts
destination.mssql.credentials="mssql://loader:<password>@loader.database.windows.net/dlt_data?connect_timeout=15&Encrypt=no"
```
should do the trick
