### ISSUE TITLE
Broken link blog dlt-lineage-support

### ISSUE THREAD

**Issue by boxydog** [dlt-hub/dlt#1186]
### Documentation description

https://dlthub.com/docs/blog/dlt-lineage-support#data-lineage has a link to https://dlthub.com/docs/dlt-ecosystem/visualizations/understanding-the-tables#data-lineage, which is broken.

### Are you a dlt user?

I'm considering using dlt, but the documentation is unclear.

**Comment by VioletM** [comment]
Hi @boxydog thanks for pointing this out!
The right like is this one: https://dlthub.com/docs/general-usage/destination-tables#child-and-parent-tables

We have PR fixing broken links ready: https://github.com/dlt-hub/dlt/pull/1166
So links would be fixed as soon as it's merge!

**Comment by boxydog** [comment]
Thanks @VioletM.
