### ISSUE TITLE
Intermittent CI failure for `test_limit_edge_cases` in async and sync resource limits

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#1213]
## Description

CI tests intermittently fail on `test_limit_edge_cases` with a limit of 10. `async_list` unexpectedly contains an extra item compared to the `sync_list`. Race condition?

Test file: tests/extract/test_sources.py
Test case: test_limit_edge_cases[10]
CI link: https://github.com/dlt-hub/dlt/actions/runs/8646067265/job/23704568405?pr=1211#step:8:1018

**Comment by rudolfix** [comment]
I know that does not sound good but let's just allow this additional element. so both lists are valid (including one causing the problem). the whole `add_limit` should be rewritten to limit async generators properly (and we wrap them in threads) and I'm not sure it makes sense now
