### ISSUE TITLE
`duckdb(":memory:")` creates an instance on disk

### ISSUE THREAD

**Issue by zilto** [dlt-hub/dlt#1216]
### dlt version

0.4.7

### Describe the problem

The [documentation](https://dlthub.com/docs/api_reference/destinations/impl/duckdb/factory#duckdb-objects) says that passing `":memory:"` to `credentials` of the duckdb destination should create an instance in-memory. This currently doesn't behave as describe and creates database on disk instead.
 

### Expected behavior

As mentioned in the docs, it should not leave a database file on disk.

### Steps to reproduce

Python script to reproduce. Passing a `duckdb` connection to `dlt` fixes the problem and leads to file on disk.

```python
import duckdb
import dlt
from dlt.destinations import duckdb as duckdb_dest

def warning():
    data = [{"a": 1}, {"a": 11}]
    pipe = dlt.pipeline(
        pipeline_name="repro",
        destination=duckdb_dest(credentials=":memory:")
    )
    pipe.run(data, table_name="repro_table")
    
    # WARNING IN TERMINAL
    # 2024-04-13 15:41:56,080|[WARNING]|11823|140366066149184|dlt|configuration.py|_path_from_pipeline:180|
    # Duckdb attached to pipeline repro in path :memory: was deleted.
    # Attaching to duckdb database 'repro.duckdb' in current folder. 
    
    with pipe.sql_client() as client:
        db_con = client.native_connection
        df = db_con.sql("SELECT * FROM repro_table").df()
        print(df)
    
    # RESULTS
    #     a        _dlt_load_id         _dlt_id
    # 0   1  1713037407.0234153  UXPSK0TEvjZIHw
    # 1  11  1713037407.0234153  n9iF1bPAfpzfaw
    
def success():
    data = [{"a": 1}, {"a": 11}]
    pipe = dlt.pipeline(
        pipeline_name="repro",
        destination=duckdb_dest(credentials=duckdb.connect(":memory:"))
    )
    pipe.run(data, table_name="repro_table")
    
    with pipe.sql_client() as client:
        db_con = client.native_connection
        df = db_con.sql("SELECT * FROM repro_table").df()
        print(df)
    
    # RESULTS
    #     a        _dlt_load_id         _dlt_id
    # 0   1  1713037484.0707414  BeTxMtE+GEI8mg
    # 1  11  1713037484.0707414  HE3kI0jYe07ogg

if __name__ == "__main__":
    warning()
    success()
```

### Operating system

Linux

### Runtime environment

Local

### Python version

3.10

### dlt destination

DuckDB

### Other deployment details

Initially encountered the bug when developing in a Jupyter notebook, but the error is reproduced with the same code in a script.

### Additional information

Passing a duckdb instance directly fixes the issue (as mentioned in the repro)

```python
pipe = dlt.pipeline(
        pipeline_name="repro",
        destination=duckdb_dest(credentials=duckdb.connect(":memory:"))
    )
```

**Comment by sultaniman** [comment]
Hey @zilto thanks for the report I was able to reproduce this and am working on the fix 
<img width="456" alt="image" src="https://github.com/dlt-hub/dlt/assets/354868/d16d7cba-6952-4a72-af87-5f6b4a417e89">
