### ISSUE TITLE
Support Merge disposition for Athena Iceberg table

### ISSUE THREAD

**Issue by nicor88** [dlt-hub/dlt#1243]
### Feature description

I would like to use merge disposition with Athena Iceberg tables. 
Athena iceberg allows to use `MERGE`, `DELETE`, `UPDATE`, and should possible to use merge disposition.

Athena External tables (also called hive) cannot support merge disposition, because merge,delete,update is not supported.

 

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

I have quite some use cases where I process data in daily batches incrementally, and I upsert the final dataset by date.

Currently I use 

Code wise looks like this:

```

source_df = ...# data from the last 7 days

wr.s3.to_parquet(
        df=source_df,
        path=f"s3://{DST_BUCKET}/{GLUE_TABLE_NAME}",
        dataset=True,
        schema_evolution=True,
        mode='overwrite_partitions',
        partition_cols=['my_date'],
        database='bronze',  # Athena/Glue database
        table=GLUE_TABLE_NAME  # Athena/Glue table
    )
```
The snippet above delete the underlying data based on my_date (that is used as a partition), then it re-insert records to the final target table based on the content of `source_df`
 

### Proposed solution

Adding **merge** disposition for athena iceberg tables should help to achieve what I want, and cover quite some use cases.

**Comment by rudolfix** [comment]
should go together with #633

**Comment by jorritsandbrink** [comment]
@nicor88 I'll close this ticket. If you have additional requirements for #633 , feel free to add them there.
