### ISSUE TITLE
[source] implement relational database source

### ISSUE THREAD

**Issue by amirbtb** [dlt-hub/dlt#125]
Hello folks !

First I want to say thank you for your work on `dlt`. The idea of a "dbt for EL" + an integration with `dbt` is just what Data Engineering needed 🙏🏽 

## Description
A lot of companies don't have an API layer on top of their applications databases. They rely on SQL queries to extract transactional data from applications databases before loading it to the datawarehouse. Maybe there is such a feature but I don't understand how to use it with `dlt`.

## Who will this benefit?
Anyone having relational databases as data sources & relying on "SQLAlchemy-like" connection & SQL to extract data. 

Thank you !

**Comment by rudolfix** [comment]
we have a simple query/table source that works with any sqlalchemy connection string (it's using `pandas` internally). the code is in the examples here:
* https://github.com/dlt-hub/dlt/blob/2f1e056c61b4913dc8a9f8bd03d01142a2116d95/docs/examples/sources/sql_query.py - the source itself
* https://github.com/dlt-hub/dlt/blob/2f1e056c61b4913dc8a9f8bd03d01142a2116d95/docs/examples/read_table.py - usage example

as you can see the source implementation is "almost" one liner :) the performance could be improved by batching and maybe direct sqlalchemy implementation. Unfortunately those examples are not distributed with the library so you may just copy the first file. We really need to think where to put built-in sources and start to distribute them...

are you planning do build something with `dlt`? the example above can get you started but we are very keen on improving our sources when people do something interesting with them

**Comment by amirbtb** [comment]
Hey @rudolfix thank you for the examples, I will try it as soon as I can. 

Yes I am actively looking for a way to perform Extract-Load (let's say the Transform is covered with `dbt`) workloads in a **serverless** fashion (Cloud Functions/Cloud Run on GCP, Lambda on AWS, etc...) so my ELT workflows don't require expensive SQL databases and Kubernetes Clusters 🤯.

We were planning to develop something similar to `dlt` in order to standardize our data extraction workflows. The notable differences are : 
- only 1 loader since my colleagues & I mainly load data as `.parquet` files in (Google Cloud Storage) buckets & use external tables on top of them to stage them in our data warehouse (BigQuery).
- use YAML to define our data sources and then run boilerplates code according to the source type, parameters, etc...

**Comment by rudolfix** [comment]
then you may be interested in the `duckdb` destination that was released today and the `dbt` support that is built in with `dlt`. with `duckdb` you can generate parquet trivially just by using `COPY TO` sql statements - and this is a feature (a `parquet` destination) that we plan to release in 1-2 weeks.
* https://dlthub.com/docs/destinations#destination-configuration
* https://github.com/dlt-hub/dlt/blob/devel/docs/examples/dbt_run_jaffle.py

this will work in lambda function. duckdb is just 1MB c++ code (if you do not know it yet) and I know that people run it on AWS lambda so GCP counterpart will work as well.

 catalogue registration (ie. AWS Glue or GCP) is also something that we look at but we didn't figure out if there's interest for it

**Comment by amirbtb** [comment]
Cool ! I'm a big fan of duckdb, I already use it as an in-memory Analytical database (for light local project) but I should explore using it in our Cloud ELT Workflows.

**Comment by amirbtb** [comment]
I'm going to close this issue since `dlt` supports relational database sources. Thank you @rudolfix 

> we have a simple query/table source that works with any sqlalchemy connection string (it's using `pandas` internally). the code is in the examples here:
> 
> * https://github.com/dlt-hub/dlt/blob/2f1e056c61b4913dc8a9f8bd03d01142a2116d95/docs/examples/sources/sql_query.py - the source itself
> * https://github.com/dlt-hub/dlt/blob/2f1e056c61b4913dc8a9f8bd03d01142a2116d95/docs/examples/read_table.py - usage example
> 
> as you can see the source implementation is "almost" one liner :) the performance could be improved by batching and maybe direct sqlalchemy implementation. Unfortunately those examples are not distributed with the library so you may just copy the first file. We really need to think where to put built-in sources and start to distribute them...
