### ISSUE TITLE
RESTClient: review raised exceptions and provide user friendly alternatives

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1281]
Several components (mostly Paginators) raise general Python exceptions (ie. `ValueError`) instead of providing actionable information on what went wrong.

Review the code base and raise customized exception
Take known user feedback in mind ie. `Better error handling: display the content of the error document if present`

**Comment by sh-rp** [comment]
One probably quite typical case is the pokemon api. We have an openapi spec which misleads the generator into mapping incorrect fields from the parent object to the child url (in the generator resource). This means rest_api tries to look up a value in the parent object which does not exist as a key there. Right now the error is obscure, what would be nice is something like: 

Error while processing child resource, expected key "id" not found in parent object of type "pokemon", available keys are: "name", "url". Please update your pokemon endpoint.

**Comment by rudolfix** [comment]
@sh-rp your feedback is implemented in `rest_api`. I added a lot of exceptions there. but they are all ValueError. We'll make an exception tree later
