### ISSUE TITLE
Snowflake destination issue: fail to execute multiple sql queries 

### ISSUE THREAD

**Issue by hengpor** [dlt-hub/dlt#1312]
### dlt version

0.4.10

### Describe the problem

There bug in snowflake destination 
https://github.com/dlt-hub/dlt/blob/1e0db2f97e14d8f54f81df8c7c0eac9556989ad0/dlt/destinations/impl/snowflake/sql_client.py#L105

num_statements=0 is hardcoded into code when query can be more than one sql queries

### Expected behavior

num_statements should the number queries

### Steps to reproduce

Running pipeline using snowflake-connector-python 2.9.0

### Operating system

macOS

### Runtime environment

Local

### Python version

3.9

### dlt destination

Snowflake

**Comment by rudolfix** [comment]
@hengpor do you have a stack trace with this bug?

`num_statements=0` is a special value for multi-statement query:
https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/cursor.py#L901

we have plenty of tests that execute multiple queries, maybe you have problem with a specific snowflake python client version?

**Comment by hengpor** [comment]
I am using snowflake connector 2.9.0 and 3.5.0 both have the same issue

**Comment by rudolfix** [comment]
@hengpor are you able to switch to "3.5.0" or newer? there are quite significant improvements from snowflake side ie. they removed pyarrow as dependency.

2.9.0 is from 2022. if you have hard requirements to use it ping me I'll try to run our tests on it. it is a first version that introduced the support for multi queries and I expect some bugs in it
