### ISSUE TITLE
Airflow deployment

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#140]
Create an airflow deployment similar to the current git actions deployment. The deployment should support

1. * [x] generation of a dag running the pipeline
2. * [x] ideally this dag should contain tasks representing resources, in the correct dependency. If not currently possible, start with just running the pipeline in a task before defining next steps.
3. * [ ] credentials should be passed into airflow or the appropriate user actions/guidance to take should be offered on CLI similar to the other deployment command.

**Comment by rudolfix** [comment]
ad 2. do you want to run the tasks in parallel or one by one? in the second case you can decompose any source into DAG tasks but sacrificing various optimizations ie. `dlt` can run any number of async/threaded data items from any number of resources in parallel, it will also get data only etc.
in the first case we would need to merge state and load packages. it would be the best to brainstorm how to do it
