### ISSUE TITLE
Set schema_contracts column to "evolve", but still can't create a new column because it's frozen

### ISSUE THREAD

**Issue by boxydog** [dlt-hub/dlt#1454]
### dlt version

0.4.7

### Describe the problem

I am running `pipeline.run(a_data_array, schema_contracts={"tables":"evolve", "columns":"evolve", "data_type":"evolve"})` but I'm still getting an error `Contract on columns with mode freeze is violated. Trying to add column col1 to table table1__subtable1 but columns are frozen..`. I thought the schema_contracts on pipeline.run overrides all existing settings? How do I get this unfrozen?

From https://app.slack.com/client/T04DHMAF13Q/C04DQA7JJN6.

### Expected behavior

Should add the column

### Steps to reproduce

- Install dlt
- Download 
[col_freeze_test.py.txt](https://github.com/user-attachments/files/15778422/col_freeze_test.py.txt), rename it col_freeze_test.py
- Download 
[freeze_test.schema.yaml.txt](https://github.com/user-attachments/files/15778434/freeze_test.schema.yaml.txt), rename it freeze_test.schema.yaml, and put it in a subdirectory `schemas/import`
- Run ./col_freeze_test.py 1
- Run ./col_freeze_test.py 2

I'd expect it to add the sub_subval2 column, but I think it will throw an error instead.

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

Made a simple one in the code.

### dlt destination

Postgres

### Additional information

This may not be a bug. However, I don't understand the behavior, and Dave on slack said filing a github issue would be a good way to pursue this. See  https://app.slack.com/client/T04DHMAF13Q/C04DQA7JJN6.

**Comment by sh-rp** [comment]
@boxydog using your code (and loading to duckdb which should not make a difference) there are no exceptions on dlt 0.4.12, so I can't reproduce this unfortunately. Could you run it on the newest dlt version and let me know if this resolves your issue?

**Comment by boxydog** [comment]
When I upgrade to 0.4.12, reset all state, and try this again, I also can no longer reproduce the issue. Thanks for looking.

**Comment by boxydog** [comment]
And when I tried it with 0.4.7, I can also no longer reproduce the issue. I wonder if sync-ing my state helped. Hard to tell.

**Comment by sh-rp** [comment]
@boxydog glad to hear it works now :)
