### ISSUE TITLE
snowflake requires a password when authenticator is set

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1465]
### dlt version

0.4.12

### Describe the problem

our snowflake connector requires password or private key to be set like below:
```python
def on_resolved(self) -> None:
        if not self.password and not self.private_key:
            raise ConfigurationValueError(
                "Please specify password or private_key. SnowflakeCredentials supports password and"
                " private key authentication and one of those must be specified."
            )
```
if people use `authenticator` ie set to `oauth2` this condition forces them to pass a fake password just to unlock this option

Two other problems were also reported:
1. no way to pass auth token directly in credentials
2. token is not masked when displaying connection string

### Expected behavior

Setting authenticator should allow configurations without password / private keys

### Steps to reproduce

Please write a test to reproduce this problem

### Operating system

Linux

### Runtime environment

Local

### Python version

3.11

**Comment by s-jorgenfroland** [comment]
Im not an expert coder, so bare with me on this. But it also looks like there is no support for "token"-parameter in class SnowflakeCredentials.

**Comment by s-jorgenfroland** [comment]
I have tried printing the conn_params before the connect()-function is called here: https://github.com/dlt-hub/dlt/blob/23c6365310d60ed86e16b25196ae4e41e71e8b3b/dlt/destinations/impl/snowflake/sql_client.py#L47

and token is not among the parameters, even when I have a working "token" value in the secrets.toml-file.

**Comment by s-jorgenfroland** [comment]
We have looked into this today, and suggest a change to configuration.py for snowflake.

Adding token to the SnowflakeCredentials class:

```
authenticator: Optional[str] = None
token: Optional[str] = None
private_key: Optional[TSecretStrValue] = None
```

and also adding a check in to_connector_params()-function setting the token, like this:

```
if self.authenticator:
     conn_params["authenticator"] = self.authenticator
        
if self.authenticator == "oauth":
     conn_params["token"] = self.token

if self.application != "" and "application" not in conn_params:
     conn_params["application"] = self.application
```

...worked at our end. "token"-param in the secrets.toml was picked up and used correctly.
