### ISSUE TITLE
support csv file format in snowflake

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1470]
**Background**
It looks like `csv` is still the fastest (like 3x faster: https://community.snowflake.com/s/article/How-to-Load-Terabytes-Into-Snowflake-Speeds-Feeds-and-Techniques) so it makes sense to enable it (since we have support to write csvs already)

**Tasks**
1. * [x] enable csv as supported file format
2. * [x] add csv option to COPY job of snowflake, make sure you configure it for how our writers work
3. * [x] find tests we use for postgres and run them on snowflake. make sure that arrow and python writers work

Previously, the biggest problem was to recognize quoted empty strings as NULL. fingers crossed Snowflake supports that (FORCE NULLs on postgres) - see Postgres copy command

**Comment by krishna06nani** [comment]
Hi @rudolfix, I see this issue is not assigned to any developer. I have 4 years of experience on ETL tools(Mulesoft and Azure synapse) + Snowflake. Can i take this up?

**Comment by sh-rp** [comment]
@krishna06nani thanks for the offer, It already has been worked on in https://github.com/dlt-hub/dlt/pull/998. If you'd like to help out, find us in our community and we can talk about what you might implement :)
