### ISSUE TITLE
duckdb database location challenging to find and understand

### ISSUE THREAD

**Issue by TyDunn** [dlt-hub/dlt#148]
Right now, after running a pipeline that loads to DuckDB, you get a message that says `the duckdb destination used duckdb:////users/<username>/.dlt/pipelines/chess/quack.duckdb location to store data`.

As a new dlt user, I would have expected the DuckDB database to be in the same directory as my pipeline script. If we were to do that, we would need to make sure that the DB is not committed in Git, so we should probably also add it to the `.gitignore` file?

**Comment by rudolfix** [comment]
@TyDunn implementation tasks
* [ ] create the `duckdb` database file in the current working folder (place from which you call the python script)
* [ ] name the database after the pipeline. for chess pipeline it is `chess.py`
* [ ] update the docs
