### ISSUE TITLE
Integrate REST API generic source into dlt core

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#1484]
## Background

- Currently the [REST API generic source](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api) is available and installable via `dlt init` command which fetches the code of the source from https://github.com/dlt-hub/verified-sources repo

## Proposed change

- Include REST API source as a core feature of dlt
- Starting from dlt v1.0, the `dlt init rest_api` command will not copy from the verified-sources repo but only create a sample pipeline wich imports the rest_api source from dlt-core.

## Expected benefits

- Simplified setup for users by pre-integrating common functionalities. 
- Simplifies setup for dependent libraries and projects.
- Simplifies development by reducing the duplicate tests

## Considerations

- One benefit of having REST API as a source is that when initiating it, the user gets a file with a sample configuration (https://github.com/dlt-hub/verified-sources/blob/master/sources/rest_api_pipeline.py), this is very useful for a quick start and the same functionality is needed when integrating REST API source into the core. 

## Implementation details

- [x] create new module `dlt.sources.rest_api` which contains the implementation currently residing in verified-sources
- [x] copy the test suite from verified-sources
- [x] merge the test suites of the RESTClient and the rest_api source. The `mock_api_server` for the RESTClient is more refined and is preferred in case of conflicts
- [x] consider renaming test modules (offline_tests are integration tests)
- [ ] consider renaming rest_api_source and rest_api_resources to e.g. source/resource or create_source/create_resources 
- [x] update test suite so that CI runs tests for all sources
- [x] update CI so that it executes the test suite properly

**Comment by willi-mueller** [comment]
@burnash Regarding renaming of the function `rest_api_source()` `rest_api_resources()`:

As of now, we use it as follows:
```py
from dlt.sources.rest_api import rest_api_resources, rest_api_source

source = rest_api_source(config)
```
The advantage is that because of the word "rest_api" the code is clear even when the import statement is not.


Alternatively, this could be nice:
```py
from dlt.sources.rest_api import create_resources, create_source

source = create_source(config)
```
The advantage is that the code is less redundant if we read it with the import statement. Is it worth the breaking change?

**Comment by burnash** [comment]
@willi-mueller yes, I like this "create_*" names, as repeating "rest_api" in the function names seems redundant to me. @rudolfix should we do the same for sql and filesystem?
