### ISSUE TITLE
allow multiple uses of `dlt init` and wire the pipelines repo to it

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#149]
**Motivation**
We want to distribute [pipelines](https://github.com/dlt-hub/pipelines) as [customizable and hackable source code](https://github.com/dlt-hub/pipelines/blob/master/DISTRIBUTION.md). That requires several changes to `dlt init`.

**Tasks**
1. * [x] allow the `dlt init` to be executed several times in the same folder
2. * [x] single use of `dlt init` must be backward compatible with the old behavior described in docs
3. * [x] `dlt init` will clone and inject code from `pipelines` repo. the `init` repository will be discontinued
4. * [x] multiple code files and sources/resources declared in several files will be allowed
5. * [x] `requirements.txt` of the initialized pipelines will be merged with the existing ones (or with pyproject.toml)
6. * [x] `secrets.toml` and `config.toml` will be updated and not overwritten. existing credentials and keys will not be touched (warning will be issued)
7. * [x] simple code update strategy will be implemented (specified below)
8. * [x] `dlt init --list-pipelines` will show all existing pipelines in the repo. (we may display the first line of docstring if pipeline provides one)
9. * [x] `dlt init` should be available as python api so it is easy to issue it in colab [optional]

**Code update strategy**
We allow for simple code update if the pipeline code changes
1. * [x] if the example file is deleted then it won't be created again
2. * [x] if any of the code files is modified it won't be updated. instead the command will ask if to leave or replace it
3. * [x] for each code file we'll store the commit hash and file hash in the `pipelines` repo to allow better merge strategies later

**Tests**
* [ ] extend existing tests to run the command against all possible pipelines in the `pipelines` repo
* [ ] extend the `pipelines` CI to do the same when pipeline is comitted

**Comment by rudolfix** [comment]
@TyDunn @adrianbr please review

**Comment by TyDunn** [comment]
This looks good to me
