### ISSUE TITLE
Allow primary key of the table to be set in the resource.

### ISSUE THREAD

**Issue by redicane** [dlt-hub/dlt#151]
It would be nice to be able to declare the primary key inside the resource so the schema in the database is better saved.

**Comment by rudolfix** [comment]
@redicane what do you mean? in the `@dlt.resource` or somewhere else? please give an example

**Comment by redicane** [comment]
I am not really sure on the implementation but in the @dlt.resource you could add it as an option:

@dlt.resource(name="...", primary_key="id"), in which case if there is a column with the name id it would be recognized as the primary key or part of a composite primary key.

**Comment by rudolfix** [comment]
done :)
