### ISSUE TITLE
Flexible naming on stage schema

### ISSUE THREAD

**Issue by shion-w** [dlt-hub/dlt#1519]
### Feature description

Currently there is no flexibility in naming the stage schema which defaults to `{name}_STAGING`. While this is great for general use, it might be beneficial to give users the flexibility to define their own name for the staging schema. 

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Internally we have a strict naming standards for our schemas in Snowflake which prevents the implementation of dlt. With this in place, it would allow dlt to be implemented in stacks where naming standards are strict. 

### Proposed solution

I think from an implementation side, it might be beneficial to add it in the pipeline declaration
```
pipeline = dlt.pipeline(destination='snowflake', dataset_name='raw_salesforce', stage_dataset_name='stage_salesforce')
```

### Related issues

No

**Comment by rudolfix** [comment]
@shion-w 
this is solved by #1555 and implemented like in #919 (via config or via destination factory)
to be released in 0.5.1
