### ISSUE TITLE
Make the dlt resources failure resilient.

### ISSUE THREAD

**Issue by redicane** [dlt-hub/dlt#152]
It would improve user experience if a single resource failing wouldn't stop all the other resources from running. This could be an option as well.

**Comment by rudolfix** [comment]
could you give an example, as a user, how the interface should look like? `fail_mode` in `dlt.resource` decorator? (ie ignore | abort). unfortunately it is impossible to retry generators or iterators but we can ignore the exceptions and close them on failure. the retry must be done in the code of the source ie. by using #147

**Comment by redicane** [comment]
I actually had this is mind as a general setting in dlt.source or config, but it might be better to specify the fail_mode for every resource with the default being ignore. I think this should be good.

**Comment by rudolfix** [comment]
Do you have any practical use case or problem that it solves? I like the idea as a feature but I do not see really an application. Typically you want all or nothing (atomic) data to be loaded and this is what `dlt` currently does.
Where having "optional" resource helps? Mind that you can always [select which resources to load](https://github.com/dlt-hub/dlt/blob/devel/docs/technical/create_pipeline.md#multiple-resources-and-resource-selection-when-loading)

**Comment by redicane** [comment]
I think this would be perfect when the user expects to be able to load a resource but for various reasons is not able to: missing access, improper naming resulting in an error 404 API call, etc. The benefit being in cases where the user is doing daily loads using Airflow, it would be quite disappointing to find out hours after that nothing was loaded due to a small naming mistake or similar stuff. Obviously this can also be done in a try, except inside the resource but I think it would make hackability easier
