### ISSUE TITLE
Create profile-based destination db schema names

### ISSUE THREAD

**Issue by JoBerkner** [dlt-hub/dlt#1520]
### Feature description

When working in a team in a data setup the data layer in a shared database (be it development environment or Prod environment) should have an isolated data space for each member of the team. When I test my code on a shared development database, I want to make sure, that the data that I push into somewhere is located somewhere, where it doesn't interfere with the work of other. For example, if I decide to name a destination in my dlt pipeline `customers` and another colleague decides to use this name at the same time, we would have a conflict while developing our dlt pipeline. In dbt, there is the [custom schema](https://docs.getdbt.com/docs/build/custom-schemas) setup, which allows to use the same naming convention in the code but under the hood, the resulting schema gets a prefix based on the individual profile setup. This feature would make it easier to work with dlt as well and in my opinion should be added. 

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Currently, two colleagues wouldn't be able to create a code with the same destination's dataset name when developing a pipeline as they both would overwrite each other's table content while developing.

### Proposed solution

Add a `profile` attribute to the `secrets.toml` which is then used to prefix destination dataset names (like database schemas).

**Comment by rudolfix** [comment]
@JoBerkner why setting the `dataset_name` on the pipeline is not sufficient? if you set it to the user name, `dlt` will create a database schema with this name in the destination and all users will be isolated. btw. I think user isolation is where the idea of database schema is coming from...

**Comment by JoBerkner** [comment]
@rudolfix  it would be sufficient somehow, but it means that everyone should always remember adding it as a prefix to every pipeline's dataset name that is created. If they don't, we see schemas in the database where we don't know at first hand who created it plus the possibility to overwrite other's work. It would be great if dlt does it just under the hood without worrying about it and only specifying the profile in the connection setting once.

**Comment by rudolfix** [comment]
@JoBerkner this makes sense! a configurable prefix is not hard to add!

**Comment by JoBerkner** [comment]
@rudolfix That sounds good. Just to make sure: To me, it makes most sense to place the dataset_name_prefix config in the `secrets.toml` because it is part of our gitignore in contrast to the `config.toml` which stores crucial resource settings every developer should have. But if it will be possible to place it in either I am totally fine with it
