### ISSUE TITLE
Using dlt.current.pipeline() produces "TypeError: 'module' object is not callable"

### ISSUE THREAD

**Issue by boxydog** [dlt-hub/dlt#1574]
### dlt version

0.5.1

### Describe the problem

When I call `dlt.current.pipeline()` I get `TypeError: 'module' object is not callable`

Sure enough, in my debug console, it looks like a module:

```
>>> dlt.current.pipeline
<module 'dlt.pipeline.pipeline' from '...myproject/.venv/lib/python3.11/site-packages/dlt/pipeline/pipeline.py'>
```

### Expected behavior

Should return the current pipeline.

### Steps to reproduce

Filed from slack thread: https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1720550278808349

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

My own source to read an excel file.

### dlt destination

Postgres

### Additional information

On slack, Alena Astrakhantseva said:

> Yeah, sorry we know about this problem, could please create an issue
> to fix it now you can use dlt.pipeline().sql_client()

**Comment by rudolfix** [comment]
@boxydog this is already reported here: #1512 

as a workaround you can:
```
import dlt


current_pipeline = dlt.pipleine()
```

**Comment by boxydog** [comment]
Thanks!

Since it's already been filed, I'll close this one.
