### ISSUE TITLE
ClickHouse shard error when creating table

### ISSUE THREAD

**Issue by gallejesus** [dlt-hub/dlt#1595]
### dlt version

0.4.12

### Describe the problem

Hello, I'm running a very basic scenario to test dlt against ClickHouse database using this [tutorial](https://dlthub.com/docs/pipelines/rest_api/load-data-with-python-from-rest_api-to-clickhouse). The error I'm facing I suspect it's related with the table engine created by default in the DB, but I'm not able to change it. I have added in secrets.toml the table_engine_type = "merge_tree" configuration option, but I'm getting the following error:
`<class 'dlt.destinations.exceptions.DatabaseTransientException'>
Code: 139.
DB::Exception: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/{shard}/sandbox_jmgallego/rest_api_data___dlt_sentinel_table' at '20' or macro is not supported here. Stack trace:
`        
As I said, I guess it's because it lacks shard information when creating the replicated table and  don't believe it to be database related.

Is there anything I'm missing in configuration? Thank you!

### Steps to reproduce

I would expect the table to be created in the destination database and data to be inserted.

### Operating system

Linux

### Runtime environment

Local

### Python version

3.10

### dlt data source

API source

### Other deployment details

I'm using ClickHouse destination.

**Comment by Pipboyguy** [comment]
@gallejesus I'm unable to replicate your reported exception in the latest version of dlt. Kindly try again with latest version and share full script and config + secrets.toml with sensitive info redacted?

Thank you!

**Comment by rudolfix** [comment]
the affected code was already rewritten from the moment the bug was reported. let's close it, we can always reopen when we get more info
