### ISSUE TITLE
Allow Custom Override of `_dlt_valid_from` and `_dlt_valid_to` Timestamp in SCD2 Incremental Loading

### ISSUE THREAD

**Issue by muuuuwa** [dlt-hub/dlt#1601]
### Feature description

Currently, when using the SCD2 strategy for incremental loading in dlt, the `_dlt_valid_from` and `_dlt_valid_to`  timestamp is automatically set to the time the pipeline is executed. This can cause issues when records need to reflect a specific historical period rather than the pipeline execution time.

Request:

I would like to request a feature that allows users to override the _dlt_valid_from/to timestamp with an arbitrary value. This would provide more flexibility and control over the data's validity periods, making it possible to accurately represent historical changes.

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

When processing historical data snapshots, it is often necessary to set specific `_dlt_valid_from` and `_dlt_valid_to` timestamps to reflect accurate validity periods. The ability to manually set this value would help maintain the integrity of historical data and ensure that the SCD2 strategy works as intended.

### Proposed solution

Allow the `_dlt_valid_from` and `_dlt_valid_to` timestamp to be overridden by specifying it as a parameter when executing the `dlt` command.

**Comment by rudolfix** [comment]
@muuuuwa I think you can already do that
https://dlthub.com/docs/general-usage/incremental-loading#example-configure-validity-column-names

so you can bring your validity columns and also your own record hash. is this what you need?

**Comment by muuuuwa** [comment]
@rudolfix Thank you for your comment.Thank you for your comment.

I checked the link you shared. It explains how to change column names like `_dlt_valid_to` and how to modify the `active_record_timestamp`, which is set to NULL by default. However, my feature request is about allowing the **value** assigned to the column equivalent to `_dlt_valid_to` to be configurable, which is different from the content described in the link.

**Comment by muuuuwa** [comment]
The content of the Feature Request might have been unclear, so please allow me to provide additional explanations with sample code and the resulting output.

### Code executed on the first run
```python
import dlt

DUCKDB_PATH = (
    "/hogehoge/sample_pipeline.duckdb"
)

@dlt.resource(write_disposition={"disposition": "merge", "strategy": "scd2"})
def dim_employee():
    # initial load
    yield [
        {
            "employee_id": 1,
            "name": "John Doe",
            "section": "Sales Department",
            "updated_at": "2024-04-01T00:00:00Z",
        },
        {
            "employee_id": 2,
            "name": "Jane Smith",
            "section": "Sales Department",
            "updated_at": "2024-04-01T00:00:00Z",
        },
    ]


pipeline = dlt.pipeline(
    pipeline_name="sample_pipeline_00",
    destination=dlt.destinations.duckdb(DUCKDB_PATH),
    dataset_name="raw",
)

# first run at 2024-07-18 14:06:02.748 +0000
info = pipeline.run(dim_employee())
print(info)
```

### Result of the first run:

```
_dlt_valid_from              |_dlt_valid_to|employee_id|name      |section         |updated_at                   |_dlt_load_id     |_dlt_id       |
-----------------------------+-------------+-----------+----------+----------------+-----------------------------+-----------------+--------------+
2024-07-18 14:06:02.748 +0000|             |          1|John Doe  |Sales Department|2024-04-01 00:00:00.000 +0000|1721311562.748009|OIuAzDIDQ/GW+g|
2024-07-18 14:06:02.748 +0000|             |          2|Jane Smith|Sales Department|2024-04-01 00:00:00.000 +0000|1721311562.748009|8z6gD/mQsaY75A|
```

### Code executed on the second run:

```python
# ...
    # 2nd data
    yield [
        {
            "employee_id": 1,
            "name": "John Doe",
            "section": "Planning Department",
            "updated_at": "2024-05-02T00:00:00Z",  # He was moved to the Planning Department on 2024-05-02
        },
        {
            "employee_id": 2,
            "name": "Jane Smith",
            "section": "Sales Department",
            "updated_at": "2024-04-01T00:00:00Z",
        },
    ]


# ...

# 2nd run at 2024-07-18 14:10:58.717 +0000
info = pipeline.run(dim_employee()
print(info)
```


### Result of the second run:

* The value of `_dlt_valid_to` is set to the time when the pipeline was executed the second time.  I would like to change this value to an arbitrary value (e.g., 2024-06-01T00:00:00Z).
* Similarly, the value of `_dlt_valid_from` is set to the time when the pipeline was executed the first time. I would like to change this value to an arbitrary value (e.g., 2024-04-01T00:00:00Z).

```
_dlt_valid_from              |_dlt_valid_to                |employee_id|name      |section            |updated_at                   |_dlt_load_id     |_dlt_id       |
-----------------------------+-----------------------------+-----------+----------+-------------------+-----------------------------+-----------------+--------------+
2024-07-18 14:06:02.748 +0000|2024-07-18 14:10:58.717 +0000|          1|John Doe  |Sales Department   |2024-04-01 00:00:00.000 +0000|1721311562.748009|OIuAzDIDQ/GW+g|
2024-07-18 14:06:02.748 +0000|                             |          2|Jane Smith|Sales Department   |2024-04-01 00:00:00.000 +0000|1721311562.748009|8z6gD/mQsaY75A|
2024-07-18 14:10:58.717 +0000|                             |          1|John Doe  |Planning Department|2024-05-02 00:00:00.000 +0000|1721311858.717105|hWNElTvB14KEGQ|

**Comment by VioletM** [comment]
Also the link to the corresponding Slack discussion https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1720787605031039

**Comment by rudolfix** [comment]
@jorritsandbrink could you please take a look? maybe we need another config option in write disposition which is a timestamp or callback to a function that will create it at the runtime. Please write down an implementation idea and we'll schedule that to be implemented later. thanks!

**Comment by jorritsandbrink** [comment]
Let's make sure we're on the same page.

> I would like to change this value to an arbitrary value (e.g., 2024-06-01T00:00:00Z)

How is the _arbitrary value_ determined? I see three options:

1. value based on data
    - i.e. on the `updated_at` column in the example
2. value configured in resource
    - i.e. something like `@dlt.resource(write_disposition={"disposition": "merge", "strategy": "scd2", "boundary_ts": "2024-04-01T00:00:00Z"})`)
3. value determined by function, function configured in resource
    - i.e. something like `@dlt.resource(write_disposition={"disposition": "merge", "strategy": "scd2", "boundary_ts": a_python_function})`)

Note that:
- Option 1 requires awareness of the natural key (i.e. `employee_id` in the example). We're currently not keeping track of it, but we could add a `natural_key` column hint.
- `boundary_ts` is used as both "valid from" for the new active records and "valid to" for retired records. I don't think setting them separately makes sense.

@muuuuwa I understand you're looking for option 2. Is that correct?

**Comment by muuuuwa** [comment]
@jorritsandbrink 
> I understand you're looking for option 2. Is that correct?
Yes, that is correct! Thank you for confirming.

**Comment by jorritsandbrink** [comment]
@muuuuwa thanks :)

@rudolfix here are my suggestions for the public API and implementation:

### Public API

Add optional `boundary_ts` argument to `write_disposition` dictionary.

```py
@dlt.resource(
    write_disposition={
        "disposition": "merge",
        "strategy": "scd2",
        "boundary_ts": "2024-04-01T00:00:00Z"  # accept date(time) string or object
    }
)
```

If `boundary_ts` is provided we use it, else we default to using the load package `created_at` timestamp (which is what we're currently always doing).

The name `boundary_ts` is the best I could come up with. We also use it internally. If anyone knows a better name, please suggest.

### Implementation

Persist user-provided `boundary_ts` as table-level x-hint `x-boundary-ts` in the root table schema and pick this value up in `gen_scd2_sql`.

`boundary_ts` is likely different for each pipeline run. Is it okay to use the schema for such dynamic values?

**Comment by KkazeKa** [comment]
what would be helpful is to set the _dlt_valid_from filed to the source value of a present created_at or updated_at field.
im sourcing from mongo and i want to reflect the historical data in my fact table , but i only get the products that are present in a transaction run after the pipline run.

**Comment by jorritsandbrink** [comment]
@KkazeKa that corresponds to option 1 in my earlier [comment](https://github.com/dlt-hub/dlt/issues/1601#issuecomment-2248545639), correct?

**Comment by KkazeKa** [comment]
> @KkazeKa that corresponds to option 1 in my earlier [comment](https://github.com/dlt-hub/dlt/issues/1601#issuecomment-2248545639), correct?

to be more precise i have read the documentation and searched through slack and found that the _dlt_valid_from and _dlt_valid_to are set to the time of running the pipeline not the actual date of update in the source if there is one or with an unchanged record , for example a product in the source has a created at date when running the pipeline the _dlt_valid_from dosent reflect the actual date of validity in the source it gets set to the date of running the pipeline the same with updating a product in the source when running the pipeline after some time the _dlt_valid_to will be set to the time of the pipeline run.

**Comment by KkazeKa** [comment]
> @KkazeKa that corresponds to option 1 in my earlier [comment](https://github.com/dlt-hub/dlt/issues/1601#issuecomment-2248545639), correct?

yes option 1 it is .
