### ISSUE TITLE
rate limitation for table updates

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#161]
When loading to bigquery with dlt, we got the error
`google.api_core.exceptions.BadRequest: 400 Exceeded rate limits: too many table update operations for this table. `
docs:
https://cloud.google.com/bigquery/quotas#load_job_per_table.long

It seems it's about the nr of ddl changes per second. We need to add a rate limitaiton for these requests so they do not fail.

**Comment by rudolfix** [comment]
@adrianbr where's the stack trace? I can't say what is going on. `dlt` deals with the rate limitations when loading to tables (there's limit on daily loads) by raising transient exception. I dealt with that a lot in axies infinity. we just need to implement a retry with proper backoff on load.

regarding the load IDK. it should happen when schemas are migrated if this is so. please send me a stack trace.

also I think to get there you must do something weird like pounding bigquery from 50 parallel Airflow tasks. right?

**Comment by adrianbr** [comment]
resolved
