### ISSUE TITLE
Issues with configuration ingestion

### ISSUE THREAD

**Issue by BearDimonR** [dlt-hub/dlt#1610]
### dlt version

0.5.1

### Describe the problem

Ingestion of `extract`, `normalize`, and `load` parameters doesn't seem to work properly. 

I have set the following configurations for my run and still got the default parameter used.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/14fb7268-6153-4c35-8f8c-555334b6c42e">

### Expected behavior

All configurations applied properly

### Steps to reproduce

Just debug the execution of any of the specified methods and see that default parameters are resolved for some reason.

### Operating system

macOS

### Runtime environment

Local

### Python version

3.10

**Comment by rudolfix** [comment]
@BearDimonR 
`dlt` looks for config.toml in `.dlt` folder relative to the current working directory. If you run your pipeline script from a different folder ie `python ./script/pipeline.py` it will look in `.` not in `scripts` where your python file is.

you can also try the following: set one of the configs as env variable ie `LOAD__WORKERS=50 python pipeline.py` to see if that works
