### ISSUE TITLE
File not found error intermittently ( FileNotFoundError: [Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by axellpadilla** [dlt-hub/dlt#1619]
### dlt version

0.5.1

### Describe the problem

This issue appears to be more constant when there are multiple instances of dbt running a pipeline, apparently a needed file is removed before the pipeline needs it.

### Expected behavior

This apparently stops the pipeline, it should work even when multiple instances are running a pipeline.
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.dlt/pipelines/<pipeline_name>/load/normalized/1721403810.3061225/new_jobs/<table_name>.8c411f3418.0.sql' -> '/home/<user>/.dlt/pipelines/<pipeline_name>/load/normalized/1721403810.3061225/started_jobs/<table_name>.8c411f3418.0.sql'

 File "/usr/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/main_dagster_dev/.venv_main_dagster/lib/python3.12/site-packages/dlt/common/runners/runnable.py", line 60, in _wrap
    return f(rid, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/main_dagster_dev/.venv_main_dagster/lib/python3.12/site-packages/dlt/load/load.py", line 193, in w_spool_job
    self.load_storage.normalized_packages.start_job(load_id, job.file_name())
  File "/opt/main_dagster_dev/.venv_main_dagster/lib/python3.12/site-packages/dlt/common/storages/load_package.py", line 424, in start_job
    return self._move_job(
           ^^^^^^^^^^^^^^^
  File "/opt/main_dagster_dev/.venv_main_dagster/lib/python3.12/site-packages/dlt/common/storages/load_package.py", line 699, in _move_job
    self.storage.atomic_rename(
  File "/opt/main_dagster_dev/.venv_main_dagster/lib/python3.12/site-packages/dlt/common/storages/file_storage.py", line 188, in atomic_rename
    os.rename(self.make_full_path(from_relative_path), self.make_full_path(to_relative_path))

### Steps to reproduce

Running multiple instances of dbt, multiple fails and multiple pass, same error for all that failed.
In this case I'm using dagster to execute it.

### Operating system

Linux, Windows

### Runtime environment

Virtual Machine

### Python version

3.11

### dlt data source

mongodb

### Other deployment details

This is using mongodb source to mssql but I don't that should make a difference, python 3.12.4 but looks like not related.

### Additional information

Workarounds, looks like limiting the instances to just 1 at the time avoids the issue.

**Comment by auguste-elax** [comment]
Same here - orchestrating dlt (0.4.12) with dagster (1.7.7)

**Comment by axellpadilla** [comment]
this continues using dagster 1.7.15 and now it also fails when the data is more than a million rows even not on parallel, maybe is related to the way dagster starts a new process, dlt isn't yet fully compatible?, but didn't try orchestrating manually o new process.

**Comment by axellpadilla** [comment]
While this doesn't explain why even on sequential mode is failing with the same error, for any one getting here, on parallel this is because you can't run same name pipelines on the same machine (well, you can, but is not defined or tested) , even if you have different resources running, this can happen if you created assets instead of multi assets for that pipeline, using customized logic, on this dagster scenario and consider the same logic to any other, (for example running the same name pipeline on two bashs concurrently.)

More here: [Slack](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1710717450002699?thread_ts=1710513187.652559&cid=C04DQA7JJN6)

**Comment by auguste-elax** [comment]
Thanks for the link @axellpadilla ! I was indeed running parallel jobs under the same pipeline name - will create a specific pipeline for each table. Thanks!

**Comment by axellpadilla** [comment]
What was happening on the millions rows tables was that I have two instances, one for dev and prd targets, had to change the pipeline name conditionally by target because those pipelines fail if the instance starts when the other is already running.
