### ISSUE TITLE
Update RESTClient range paginators to support stopping after empty pages

### ISSUE THREAD

**Issue by timoguin** [dlt-hub/dlt#1637]
### Feature description

Update RESTClient's [PageNumberPaginator](https://github.com/dlt-hub/dlt/blob/0d955dee409498824de140490462480625e51b77/dlt/sources/helpers/rest_client/paginators.py#L177) to optionally stop paging after receiving empty pages.

I'm unsure if other paginators need this same functionality. Perhaps it needs to be added to the base `RangePaginator` class.

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

I am pulling data from a few REST APIs that do not include the information necessary to determine the total number of records or pages. Setting the max number of pages isn't sufficient because the REST helper will keep sending requests up to the max page limit, even if everything past the first page is empty.

### Proposed solution

Add a boolean keyword argument to the `PageNumberPaginator` (or its base class `RangePaginator`) called `stop_after_empty` that is `False` by default.

When it is true, consider the paging complete when the first empty page is received.

**Comment by willi-mueller** [comment]
Thank you for your feature request @timoguin!
In the specification, you wrote that the default for this new flag should be `False`. I wonder whether defaultign to `True` would be more practical. 

Have you encountered a case where a page delivers empty results but the next page is not empty? 

What do you think @burnash?

If you like, please review this implementation: https://github.com/dlt-hub/dlt/pull/1677

**Comment by burnash** [comment]
Agree with @willi-mueller, practically it makes sense to stop after an empty page by default. I'm curious about your experience @timoguin

**Comment by timoguin** [comment]
@burnash @willi-mueller I only proposed setting it to `False` to retain the current default behavior, but I agree that it makes sense to stop after empty pages by default.
