### ISSUE TITLE
Helper that returns `delta` tables created by pipeline as `DeltaTable` objects

### ISSUE THREAD

**Issue by jorritsandbrink** [dlt-hub/dlt#1651]
### Feature description

Delta tables need management. The `DeltaTable` [class](https://delta-io.github.io/delta-rs/api/delta_table/) in `delta-rs` has useful methods such as `optimize.compact()`, `optimize.z_order()`, and `vacuum()`.

This functionality should be easily accessible to dlt users.

My suggestion is to expose a helper method that returns Delta tables created by a pipeline as `DeltaTable` object:

```py
get_delta_tables(
    pipeline: Pipeline, *tables: str
) -> Dict[str, DeltaTable]
```

This would enable the user to do things like:

```py
import dlt
from dlt.common.libs.deltalake import get_delta_tables

@dlt.resource(table_format = "delta")
def foo():
    yield {"foo": 1., "bar": 2, "baz": 3}

@dlt.resource(table_format = "delta")
def bar():
    yield {"foo": 1., "bar": 2, "baz": 3}

@dlt.source
def delta_source():
    return [foo(), bar()]

pipeline = dlt.pipeline(destination="filesystem")

pipeline.run(delta_source())

delta_tables = get_delta_tables(pipeline)

# operations on all tables
for dt in delta_tables.values():
    dt.optimize.compact(...)
    # dt.vacuum(...)
    # dt.repair(...)
    # dt.cleanup_metadata()

# operations on individual tables
delta_tables["foo"].optimize.z_order(columns=["foo", "bar"])
delta_tables["bar"].optimize.z_order(columns=["bar", "baz"])
```

### Are you a dlt user?

Yes, I'm already a dlt user.

**Comment by rudolfix** [comment]
it looks good. the only thing I'd add to the interface is an optional list of tables to be used instead of those taken from default schema.

yes there are parallels. we should somehow expose delta tables with the similar interface @sh-rp does. maybe we should add another property: `native_client` which would expose ie. authorized `pyscopg2` / `duckdb` connection, fsspec filesystem or delta-rs client.

**Comment by jorritsandbrink** [comment]
> it looks good. the only thing I'd add to the interface is an optional list of tables to be used instead of those taken from default schema.

@rudolfix You might have missed `*tables` in `get_delta_tables`:
![image](https://github.com/user-attachments/assets/8adc22b9-a1aa-4229-b986-d3039bf37915)

**Comment by Gilbert09** [comment]
I'm doing some testing with the effectiveness of running `.compact()` and `.vaccum()` this week on our existing synced data. I'll report back on the findings, but if that works, then the approach above is ideal - we'd likely run these commands every `n` syncs of data from the pipeline.

**Comment by Gilbert09** [comment]
@jorritsandbrink I've done some testing. We'll certainly need to use both `compact()` and `vacuum()` to achieve the type of performance we want. So this approach is good. Do you have an ETA for an alpha release for this? Our query times are very much like 📈 at the moment
