### ISSUE TITLE
Move `sql_database` source from verified-sources to dlt core

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#1671]
### Background

The `sql_database` source, currently lives in the [verified-sources](https://github.com/dlt-hub/verified-sources) repository. It's a critical component for many users of dlt who load data from SQL DBs. Given its importance and frequent usage, integrating this source connector directly into the dlt core simplifies the user experience and makes dependency management easier.

### Proposal

Move the `sql_database` source from the verified-sources repository into the dlt core repository.

### Tasks

- [x] Migrate code
- [ ] Migrate tests
- [ ] Update documentation: installation, usage, and examples. Add migration docs 
- [ ] Deprecate the `sql_database` source in the verified-sources repository

**Comment by rudolfix** [comment]
also let me finish #1672 first
