### ISSUE TITLE
Prevent a race condition for the first run of pipelines that write in the same schema

### ISSUE THREAD

**Issue by VioletM** [dlt-hub/dlt#1711]
### Feature description

When we have the following use case:
* several pipelines run in parallel
* they write to the same schema
* this is a first run

There could be a possibility of race conditions when pipelines are trying to create common tables:

```
_DLT_LOADS
_DLT_PIPELINE_STATE
_DLT_VERSION
``` 

This could be prevented with usage of sql statement with `IF EXISTS` clause.

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Replication of big number of tables in parallel to the same dataset.

### Proposed solution

Using `IF EXISTS` clause when creating dlt internal tables

**Comment by rudolfix** [comment]
The proposed solution:

We will render all CREATE TABLE with IF NOT EXISTS. why it is OK: 
- we read a list of existing tables from INFORMATION SCHEMA and create those that do not exist. So actual race is 99.99% prob between various dlt instances. 
- we do it only for `_dlt_` tables which have identical schemas for all concurrent pipelines so we can skip creation safely
