### ISSUE TITLE
keep the on-line docs for 0.5.x after 1.0 release

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#1712]
**Background**
We want to keep 0.5.x docs as we plan significant overhaul for 1.0. In particular the way to sync files, databases and rest apis will be documented differently.

**Requirements**
1. * [ ] allow to build and deploy docs for a particular git tag
2. * [ ] disable the search and dhelp (alternatively we could probably force algolia to index our tag)
3. * [ ] link to it from new 1.0 docs

**Comment by burnash** [comment]
One option is to do it similar to Docusaurus archived versions:

https://github.com/facebook/docusaurus/blob/473d1442b82f536749f3206bf7a628544c05ebf6/website/docusaurus.config.ts#L664-L669
