### ISSUE TITLE
Extend filesystem source and destination to work with sftp.

### ISSUE THREAD

**Issue by VioletM** [dlt-hub/dlt#1730]
### Feature description

As a user, I want to be able to load data from and to sftp server. Probably it can be done already with fsspec
- [ ] test that it could be done with existing filesystem source
- [ ] create a credentials type for sftp
- [ ] add instructions and docs how to do it

### Are you a dlt user?

Yes, I'm already a dlt user.

**Comment by rudolfix** [comment]
A few implementation hints. Look in `fsspec_filesystem`:
1. we use last modified / created timestamp for incremental loading. use `MTIME_DISPATCH` to define a mapping (I hope sftp fsspec has it - upload time should be available)
2. check `FilesystemConfiguration` on how we add credentials for particular filesystems (based on protocol)

tests:
- we have a fixture (a set of files) that we use for testing on all filesystems
- look for where `glob_files` is tested to start
- probably a local sftp server for testing is good
- I expect some problems with https certs... how self-signed certs are handled.
