### ISSUE TITLE
Support for DuckDB 1.1.0

### ISSUE THREAD

**Issue by cmcnicoll** [dlt-hub/dlt#1828]
### Feature description

Support for installing the latest versions of dlt and DuckDB.

Current error:
```
0.178 uv pip install --system -r requirements.txt
2.551   × No solution found when resolving dependencies:
2.551   ╰─▶ Because dlt[duckdb]==1.0.0 depends on duckdb>=0.6.1,<0.11 and
2.551       you require dlt[duckdb]==1.0.0, we can conclude that you require
2.551       duckdb>=0.6.1,<0.11.
2.551       And because you require duckdb==1.1.0, we can conclude that your
2.551       requirements are unsatisfiable.
```

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

I want to install the latest versions of dlt, DuckDB, dbt-core, and dbt-duckdb.

### Related issues

I found this discussion:
https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1718957863295209

**Comment by rudolfix** [comment]
@cmcnicoll right! btw. if you force new duckdb to be installed, it will work just fine. we'll use open ended dependency from now since duckdb got stable storage format
