### ISSUE TITLE
Empty Response (e.g. HTTP 204) causes ignore response_actions to fail

### ISSUE THREAD

**Issue by TheOneTrueAnt** [dlt-hub/dlt#1849]
### dlt version

1.0.0

### Describe the problem

Using the rest_api_source when specifying a response action such as `{"status_code": 204, "action": "ignore"}` if the response is empty this application fails as there is a log entry created which calls `response.json()`, this call fails throwing an exception which is unhandled. In my case this was when calling the Azure DevOps API. 

### Expected behavior

The empty response matching the status code and/or content should be ignored

### Steps to reproduce

Configure a `rest_api_source` to call an endpoint which returns no content and configure a `response_action` which should ignore it. Run the pipeline and it will fail with the error: `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### Operating system

Linux, Windows

### Runtime environment

Local

### Python version

3.10

### dlt data source

rest_api_source

### dlt destination

DuckDB, Snowflake

### Additional information

My current workaround is to override empty responses when they might occur by using the following function in the list of `response_actions` ahead of the desired ignore action:

```
def fixup_empty_response(response: Response) -> Response:
        if not response.text:
            response._content = "{}".encode("utf-8")
        return response
```
Then in my configuration I add:
```
{
...
"response_actions":[ fixup_empty_response, {"status_code": 204, "action": "ignore"}]
...
}
```

**Comment by TheOneTrueAnt** [comment]
Note the fix appears to simply be to change this line in `config_setup.py` https://github.com/dlt-hub/dlt/blob/acf1e36afdd084a3cb447c5c15c669774a61705b/dlt/sources/rest_api/config_setup.py#L509 to be `response.text`. I also wonder if logging the full content like that is always useful, maybe it should only do that if the `content` field was used in the action?

**Comment by cwe5590** [comment]
My current workaround is to override the default ignore response so as not to call response.json():

`def ignore_response(response: Response) -> None:
    logger.info(f"Ignoring response with code {response.status_code} ")
    raise IgnoreResponseException

                    "response_actions": [
                        {"status_code": 404, "action": ignore_response},
                    ],

`
