### ISSUE TITLE
Links in Tip boxes while in dark mode are hard/impossible to read

### ISSUE THREAD

**Issue by tuckerrc** [dlt-hub/dlt#1857]
### Documentation description

Like the title says, links that show in tip boxes are hard to read when in dark mode.

![2024-09-22 16 01 47 dlthub com 4a0b298bf25b](https://github.com/user-attachments/assets/59c2a9a2-7212-4349-9263-7eff043baebc)

### Are you a dlt user?

None

**Comment by burnash** [comment]
Hi @tuckerrc, thanks for bringing this up. We will address this issue as part of https://github.com/dlt-hub/dlt/issues/1698
