### ISSUE TITLE
Error loading data from MSSQL when using a compound merge key

### ISSUE THREAD

**Issue by mattgyton** [dlt-hub/dlt#1874]
### dlt version

1.0.0

### Describe the problem

After upgrading from DLT v0.4.9 to v1.0.0 I've started to get the following error when loading data from MSSQL using a compound merge key (i.e. `("FirstID","SecondID")`):

`<class 'dlt.common.schema.exceptions.UnboundColumnException'>
In schema: mssql_source: The column _first_id_second_idx in table test_import did not receive any data during this load. It is marked as non-nullable merge key and it must have values. This can happen if you specify the column manually, for example using the 'merge_key', 'primary_key' or 'columns' argument but it does not exist in the data.`

I've created a basic test script and replicated the error. I tried running the DLT script in v0.4.9 and it worked fine, then I ran it again in v1.0.0 and I got the error (with the reference to the sql_database module updated). I've hard-coded all the values so you can see exactly what I'm using.

Test SQL table:
````
USE Sandbox
GO

CREATE TABLE dbo.DltTest
(
	FirstID INT NOT NULL,
	SecondID INT NOT NULL,
	TestValue VARCHAR(100) NULL,
	UpdatedDate DATETIME NOT NULL,
	CONSTRAINT [PK_DltTest] PRIMARY KEY CLUSTERED (FirstID, SecondID)
)
GO

INSERT INTO dbo.DltTest (FirstID, SecondID, TestValue, UpdatedDate) VALUES
(1, 1, 'Test1', GETDATE()),
(1, 2, 'Test2', GETDATE()),
(1, 3, 'Test3', GETDATE()),
(2, 1, 'Test4', GETDATE()),
(2, 2, 'Test5', GETDATE()),
(3, 1, 'Test6', GETDATE())
GO
````

DLT script:

````
import dlt
from dlt.sources.credentials import ConnectionStringCredentials
from dlt.sources.sql_database import sql_table
#from sql_database import sql_table
from datetime import datetime, timezone

@dlt.source
def mssql_source(
    username = dlt.secrets.value,
    password = dlt.secrets.value,
    host = dlt.secrets.value,
    port = dlt.secrets.value
    ):
    
    credentials = ConnectionStringCredentials()

    credentials.drivername = "mssql+pymssql"
    credentials.username = username
    credentials.password = password
    credentials.host = host
    credentials.port = port
    credentials.database = "Sandbox"

    connection_string = credentials.to_native_representation()

    data = sql_table(
        credentials=connection_string,
        table="DltTest",
        schema="dbo",
        backend="pyarrow",
        chunk_size=100000,
        incremental=dlt.sources.incremental(
            "UpdatedDate", 
            initial_value=datetime(1900, 1, 1, tzinfo=timezone.utc)
        ),
    )

    data.apply_hints(
        write_disposition="merge",
        merge_key='("FirstID", "SecondID")',
    )
    yield data

pipeline = dlt.pipeline(
    pipeline_name="DltCompoundKeyTest",
    destination="snowflake",
    dataset_name="DLT_TEST",
)
pipeline.run(mssql_source())
````

### Expected behavior

Data is loaded incrementally from MSSQL into Snowflake using the compound merge key

### Steps to reproduce

See scripts above

### Operating system

Linux

### Runtime environment

Local

### Python version

3.10

### dlt data source

sql_database (MSSQL)

### dlt destination

Snowflake

**Comment by rudolfix** [comment]
@mattgyton in your example you provide the merge keys as string: '("FirstID", "SecondID")'
what you need to do is to use tuple or a list so ("FirstID", "SecondID") or ["FirstID", "SecondID"]. both merge and primary key hints accept strings for single columns and sequences for compound keys.

**Comment by rudolfix** [comment]
other question is how did it work on 0.4.9... it was not checking nullability in the normalizer for sure. but snowflake should fail when inserting data to this fake column

**Comment by mattgyton** [comment]
Hi @rudolfix, I've just re-tested using a tuple and a list and they both work fine on v1.0.0 - thanks! I also tested again on v0.4.9 using the string and it definitely works, so I have no idea why! In reality we are storing our config in a JSON object and the compound merge keys are stored like this: `"merge_key":"(\"FirstID\",\"SecondID\")"`. We then just extract that from the object, assign it to a variable and pass it in as the merge_key without explicitly converting it to a tuple or list, which worked fine previously but not in v1.0.0. Think I will just update the config to store them as a list which is much neater anyway, as I wasn't aware it would accept a list previously.

Thanks for your help!
