### ISSUE TITLE
Docs: incorrect Telemetry link

### ISSUE THREAD

**Issue by novica** [dlt-hub/dlt#1916]
### Documentation description

Docs at https://dlthub.com/docs/pipelines/rest_api/load-data-with-python-from-rest_api-to-filesystem-az#2-configuring-your-source-and-destination-credentials have a wrong link to telemetry page:

Link https://dlthub.com/docs/telemetry 

Opens:

Page Not Found

Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

### Are you a dlt user?

None

**Comment by burnash** [comment]
Thanks for reporting this @novica
