### ISSUE TITLE
When using BigQuery as a destination, there is lack of `partition_expiration_days` option in adapter

### ISSUE THREAD

**Issue by xneg** [dlt-hub/dlt#1959]
### Feature description

There is an example of using `bigquery_adapter` for BigQuery destination:
```
bigquery_adapter(data, partition="date_hired", table_expiration_datetime="2024-01-30", table_description="Employee Data")
```
Current implementation allows you to set up partition column, table expiration and table description while creating a new table from `dlt`. But there is lack of another parameter `partition_expiration_days` that is also possible to set up during table creation in BQ.

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

We need our BQ tables to be managed by `dlt` and that's why we lack the `partition_expiration_days` parameter (we need to set it up manually after table creation).

### Proposed solution

Adding new option seems pretty straightforward for BQ tables. I'll create a PR with proposed changes and tests and link it to this issue.

**Comment by rudolfix** [comment]
OK. this is easy fix (looks like it is a table prop)

**Comment by xneg** [comment]
@rudolfix wow, you beat me to it. Thank you!
