### ISSUE TITLE
Add support for Motherduck connection strings

### ISSUE THREAD

**Issue by SarhanAS** [dlt-hub/dlt#1960]
### Feature description

Motherduck uses a connection string structure not supported by dlt's sql_database source:
`md:?motherduck_token={access_token}`

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

I'm trying to use dlt's sql_database source to pipe data from Motherduck but am running into this error when trying to connect to Motherduck:
```
dlt.common.configuration.exceptions.InvalidNativeValue: ConnectionStringCredentials cannot parse the configuration value provided. The value is of type str and comes from the ('credentials',) section(s). The expected representation for ConnectionStringCredentials is a standard database connection string with the following format: driver://username:password@host:port/database.
```

### Proposed solution

Support for MotherDuck's connection string format which uses an access token instead of the required format: `driver://username:password@host:port/database`.

**Comment by rudolfix** [comment]
we support `token` now but indeed it looks like `motheduck_token` is standardized now. https://motherduck.com/docs/key-tasks/authenticating-and-connecting-to-motherduck/authenticating-to-motherduck/

let's support it on top of the token
