### ISSUE TITLE
max_table_nesting not working as expected

### ISSUE THREAD

**Issue by Hasan-J** [dlt-hub/dlt#2009]
### dlt version

1.3.0

### Describe the problem

Using the resource defined at [reduce-the-nesting-level-of-generated-tables](https://dlthub.com/docs/general-usage/resource#reduce-the-nesting-level-of-generated-tables):

```python
import dlt

@dlt.resource(max_table_nesting=1)
def my_resource():
    yield {
        "id": 1,
        "name": "random name",
        "properties": [
            {
                "name": "customer_age",
                "type": "int",
                "label": "Age",
                "notes": [
                    {
                        "text": "string",
                        "author": "string",
                    }
                ]
            }
        ]
    }
```

Running a pipeline with `max_table_nesting=1` set for the resource has no effect; the output tables still display nesting levels deeper than 1.

Pipeline
```python
resource = my_resource()
resource.max_table_nesting = 1

pipeline = dlt.pipeline(
    pipeline_name="test_pipeline", destination="postgres", dataset_name="test"
)

pipeline.run(resource)
```

Output tables:
![image](https://github.com/user-attachments/assets/d47d822d-9f99-420d-b918-fe29488492ee)

### Expected behavior

The output tables should only include these (without table `my_resource__properties__notes`):

![image](https://github.com/user-attachments/assets/f8234e7a-4a57-4482-8638-14180d8d1484)

### Steps to reproduce

Copy the code snippets provided in the problem section and run the script. For quicker testing, you can use DuckDB, which I confirm produces the same problematic behavior.

### Operating system

Windows

### Runtime environment

Local

### Python version

3.10

### dlt data source

I initially discovered the bug while working with the JIRA source, but as described in the problem, it is not specific to any particular data source.

### dlt destination

DuckDB, Postgres

**Comment by sh-rp** [comment]
I have verified this. It works when setting max_table_nesting on the source, but for some reason not for the resource.
