### ISSUE TITLE
Improve debug errors: CannotCoerceColumnException

### ISSUE THREAD

**Issue by benoitsdm** [dlt-hub/dlt#2097]
### Documentation description

Thanks for the great library, super useful.

However it's not always easy to debug.
Something that was not very clear to me: i tried to change the type of a column, from text to int.

I got CannotCoerceColumnException Cannot coerce type in table my_table column my_col existing type bigint coerced type text value: None 

I alter table to change the actual type in msqql but was thinking a None value caused an error. 
But digging in the source code, this is just not supported:

```          # we do not support changing data types of columns
            if is_complete_column(col_a) and is_complete_column(col_b):
                if not compare_complete_columns(tab_a_columns[col_b_name], col_b):
                    # attempt to update to incompatible columns
                    raise CannotCoerceColumnException(
                        schema_name,
                        table_name,
                        col_b_name,
                        col_b["data_type"],
                        tab_a_columns[col_b_name]["data_type"],
                        None,
                    )
```

Would be nice to give a more explicit error, there is no None value in my column

### Are you a dlt user?

Yes, I run dlt in production.

**Comment by rudolfix** [comment]
@benoitsdm we'll convert this error into warning. So ie. manual schema migrations are possible
