### ISSUE TITLE
Make batched loading more convenient

### ISSUE THREAD

**Issue by sh-rp** [dlt-hub/dlt#2136]
A common use case seems to be people loading large sources (such as big sql_databases) and wanting to batch the runs into multiple smaller runs. We should probably make this more convenient by:

* Improving the limit functionality to include time limits.
* Adding a very good example or a docs page that explains loading in batches for a combination of limit and incremental and multiple runs
* Possibly having some kind of mechanism that stops repeated runs once no further rows are extracted.

**Comment by sh-rp** [comment]
@loveeklund-osttra on the next pipeline run your generator will be re-opened. for what you want to achieve you'll have to use an incremental and start the generator at the right point on the next run.

**Comment by sh-rp** [comment]
I have linked a PR here which improves the add_limit and also adds a nice example for the sql_database.

**Comment by loveeklund-osttra** [comment]
Yeah that works for most usecases. I guess there are some edge cases where it wont work, like if you more records with the same incremental key than you have memory in your runtime ( could be a problem for small lambdas etc). 
You might also end up splitting up transactions from your source system to the target. 

I don't think these are huge issue and I appreciate your answers a lot. Just wanted to make you aware of some issues that might arise from this solution that I've thought about, maybe to be included in some documentation so people are aware.
