### ISSUE TITLE
dlthub.com google analytics no longer working

### ISSUE THREAD

**Issue by TyDunn** [dlt-hub/dlt#238]
`dlthub.com` no longer is no tracking google analytics. `dlthub.com/docs` is still working; however, I believe when we updated the website, we lost tracking

**Comment by TyDunn** [comment]
@rudolfix here is the GitHub issue for the telemetry improvements we would like to have ideally before we ship the first experiment on Apr 19th

**Comment by rudolfix** [comment]
fixed in https://github.com/dlt-hub/dlthub-website repo
