### ISSUE TITLE
[core] consider change to how we create FK relationships for nested JSON

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#27]
Currently we have two ways of linking:
_no primary key is defined:_
1. we always create `_record_hash` which is **unique and deterministic** for a given row and will serve as primary key. that applies to parent and child tables
2. we link child table by referring to parent `_record_hash` so no matter how deep we have the same link structure.
3. optionally the top level parent hash is propagated so each child has link to the top table

_primary key is defined:_
1. and 3 above stand
2. we keep primary key as defined in the schema and create no additional linking

see `mainnet_6_ethereum` and tables `blocks` -> `blocks_transactions` -> `blocks_transactions_logs` which all have natural key which is kept

Stitch is using similar linking concept but it propagates the top level parent key and adds lists positions 
https://www.stitchdata.com/docs/replication/loading/understanding-loading-behavior

should we maybe follow stitch? @adrianbr pls investigate

**Comment by adrianbr** [comment]
I think we should
- support hashes
- support optionally passing a root or other column as hash, consider offering smaller inside-hash keys.
- position based unpacking is a “one size fits many” that doesn’t fit all our cases, IMO it’s a nice to have to save space on keys but may be more confusing than not to general users.
https://www.notion.so/DLT-unpacker-and-loading-behavior-a974e84cad29417a9c1d1685c98f1062

**Comment by rudolfix** [comment]
json normalizer is pluggable component. we can change FK relationships by providing alternatives.
