### ISSUE TITLE
Broken image URL in Docs > Pipelines > Zendesk

### ISSUE THREAD

**Issue by tungbq** [dlt-hub/dlt#329]
Broken image in Docs > Pipelines > Zendesk:
https://dlthub.com/docs/pipelines/zendesk

![image](https://github.com/dlt-hub/dlt/assets/85242618/3899a578-5ed7-4128-a921-8b7adce24adc)

**Comment by MirrorCraze** [comment]
Hi! Can I take this issue?

**Comment by tungbq** [comment]
@MirrorCraze I'm not the maintainers, but I think you surely can pick up this to work and propose the PR!
