### ISSUE TITLE
Unpacking nested lists

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#37]
Example:

json: [{"data": ["distinct", ["field", 970, null]]}]
py dict: [{'data':['distinct', ['field', 970, None]]}]

perhaps a good option would be a kind of recursion depth selector, or a default to handle this, for example, if it cannot handle it particularly then convert it to string.

**Comment by rudolfix** [comment]
yeah we can fix that. what is needed: how to name child tables... in case above the leaf table will be named
`parent__data__list`

and contain following columns
`value` (text)
`value_int` (int)

none will be ignored until there's value. 

in fact lists containing various types are really bad pattern and the structure above should simply by transformed by `map` function on the iterator that is produced by the source

**Comment by rudolfix** [comment]
Implemented as stated above. Nested list will be unpacked to child tables whose names will be generated by adding `__list` to parent table.
Example for metabase data where we have nested list of depth 4 (huh :) )
`cards__dataset_query__query__expressions__new_repeat_sessions__list__list__list__list`
