### ISSUE TITLE
Avoid collisions at normalisation

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#423]
It is currently possible to normalise special characters such that names collide.

For example, {"na!e": "Max",  "na%e": "Germany"} woulg get loaded as "na_e": "Germany"

Desired outcome would be to load both columns, avoiding collision by implementing some kind of extra hash at the end or similar. Or hashing the special character to its code?

**Comment by rudolfix** [comment]
we have such naming convention in the examples (adds hashes to names)
