### ISSUE TITLE
detect serverless in exec_info.py

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#474]
Since we added cloud function deployment and people deploy dlt on lambda we should detect that. please add corresponding method and include them in `exec_info_names` function

**Tasks**
1. * [ ] detect running on AWS Lambda
2. * [ ] detect running on GCP cloud function

**Comment by muppinesh** [comment]
can you assign this to me @rudolfix

**Comment by rudolfix** [comment]
done! thanks @muppinesh
