### ISSUE TITLE
schema prefix should not be required

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#51]
from dlt.pipeline.typing import GCPPipelineCredentials
GCPPipelineCredentials.from_services_dict(credentials, dataset_prefix='')

currently: not passing the prefix or passing an empty string results in an error
desired: Not passing a prefix, or passing None results in no prefix being used.

**Comment by rudolfix** [comment]
this is "tip of the iceberg" issue :)

first: it will go from credentials 100%. it does not belong here
second: I always want to load data in a specified dataset/schema (no loading to public or default schema on SQL Server)

problem: how to tell that to dlt?
second problem: the pipeline can have many schema and such schemas may have tables with the same names so they must (or should) be loaded to separate datasets

the solution (that will replace existing one)
1. the pipeline has a name
2. data is loaded into dataset with the name of the pipeline
3. the default schema has no name and tables are created in such schema by default
4. if separate schema is added or requested (in `extract`), it must have name and data will be loaded into `{pipeline_name}_{schema_name}`
5. each dataset may have only one schema (but you can squeeze many sources into it as long as table names do not overlap)

@adrianbr what's your take? how we should name datasets and how we should pass such info to dlt?

**Comment by adrianbr** [comment]
IMO There is no good reason to have multiple schemas in a pipeline except for "niceness" to separate different "levels" of data such as data from metadata. If someone really needs multiple schemas, they can create views for themselves.

so I would say do not allow 4. or make it that it updates the default schema, overwriting(? or raising error) same name tables

5. Do you mean, in the context of a single pipeline, one schema per dataset? I would say 1 dataset per pipeline. We should be able to load multiple sources (or pipelines, in separate scripts) to the same schema.

**Comment by rudolfix** [comment]
This was finally resolved by making the single vs. multiple dataset as configuration option `use_single_dataset` in `PipelineConfiguration`
