### ISSUE TITLE
Add date type

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#54]
**Motivation**
low prio: I think the number of professionals who care about date storage size and care to manage it separately is in decline so consider this a low prio unless we learn otherwise. I think most people would prefer utc timestamps that they can localize in their frontend app.

why date?: Currently we only support timestamp. In most BI databases DATE costs half to store and can be more than 2x cheaper to join on (compressed value join vs calculated value join) native date than calculated date. 

**Tasks**
1. declare new schema type in dlt/common/schema/typing.py
2. map python type to schema type in `py_type_to_sc_type` function (there's TODO already)
3. map schema type to database type for each destination (ie. dlt/destinations/bigquery/bigquery.py)

optional
4. add type coercions in `coerce_value` function. from iso string and from timestamp without days part. also add coercion from date to timestamp

**Tests**
1. add cases to `py_type_to_sc_type` tests
2. add cases to `coerce_value` tests
3. look at `test_load_with_all_types` and `TABLE_ROW` fixture, add datetime to tested columns

**Comment by steinitzu** [comment]
Ran into this creating the SQL pipeline. With bigquery destination inserting a date into a timestamp column fails. Postgres coerces ISO date strings to timestamps transparently, but BQ does not.  

```
{
  "error_result": {
    "reason": "invalid",
    "message": "Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details."
  },
  "errors": [
    {
      "reason": "invalid",
      "message": "Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details."
    },
    {
      "reason": "invalid",
      "message": "Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0"
    },
    {
      "reason": "invalid",
      "message": "Error while reading data, error message: JSON parsing error in row starting at position 0: Couldn't convert value to timestamp: Could not parse '2023-02-15' as a timestamp. Required format is YYYY-MM-DD HH:MM[:SS[.SSSSSS]] or YYYY/MM/DD HH:MM[:SS[.SSSSSS]] Field: release_date; Value: 2023-02-15"
    }
  ],
  "job_start": "2023-02-15T20:47:28.770000Z",
  "job_end": "2023-02-15T20:47:29.263000Z",
  "job_id": "table_rows_3cb44720af_0_jsonl"
}
```
Is there still any want or need to support the date type?  
From my POV I deal with date a lot in databases storing music metadata, or user profiles containing "birthday" and such. But ultimately it's not crucial whether it's stored as `DATE` or `TIMESTAMP`. But should be some support for sources containing date so it's coerced to a storable type.

**Comment by rudolfix** [comment]
@steinitzu yes we still want to do it. I will add some context to the ticket. the change is simple but requires to modify a few files
