### ISSUE TITLE
dlt deletes pipeline state table

### ISSUE THREAD

**Issue by alex-harness** [dlt-hub/dlt#549]
Hello! 👋 

Ran into quite a nasty bug,

Running a pipeline with `replace_strategy = "staging-optimized"` would consistently nuke the state table in BigQuery. Naturally I have months worth of state, luckily BigQuery snapshots everything so I was able to manually rollback. I confirmed the behavior across multiple invocations.

**Comment by z3z1ma** [comment]
This source has had over 1500 executions I think. Seems somehow quite a few production tables were affected. Anything with `merge` write disposition. 🤷
