### ISSUE TITLE
Add more metadata to load info: Row counts, and any easily available statistics

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#565]
**Background**
We want to easily monitor row counts without counting from tables, and maybe even do a row count based anomaly analysis. If there are more stats we can show without adding collection overhead, let's add them

**Tasks**
This is low hanging fruit task
1. * [ ] use the `NormalizeInfo` tuple to hold dictionaries of tables with processed items
2. * [ ] in `normalize.py` gather all item counts - they are actually there and returned to main process
3. * [ ] expose NormalizeInfo in the same way we expose `LoadInfo` from `load.py`
4. * [ ] make sure that `asdict` and `asstr` are nicely implemented.
5. * [ ] the purpose of `asdict` is to create a nice table that can be loaded with `dlt` when we load trace.
6. * [ ] we need a way to expose it. currently we just expose `LoadInfo` from `run` command. the rest goes via trace. see below

**Tests and Docs**
1. * [ ] check the counts in `tests/normalize`. make sure that `asdict` and `asstr` work
2. * [ ] make sure correct counters are returned by adding checks to existing tests in `tests/pipeline` and `tests/load/pipeines`
3. * [ ] make sure that count of 0 is returned in `test_replace_table_clearing` and other tests in this file (those truncate tables)
4. * [ ] you must update `running.md` where we explain how to get LoadInfo and how to save trace. do a nice writeup on NormalizeInfo and counters

**How to expose NormalizeInfo**
`normalize` method returns it but we want to have access in run
luckily NormalizeInfo is already saved by pipeline trace which you obtain as
```
pipeline.last_trace
```
as `PipelineTrace`. please add `last_load_info`, `last_normalize_info` and `last_extract_info`. those methods will look for a trace step and get the required info out of it. this needs to be documented

**Comment by rudolfix** [comment]
@adrianbr you could get those counts before they are loaded. no mechanism or that yet, except executing extract/normalize/load one byone
