### ISSUE TITLE
[QUESTION] Auditing dlt Code

### ISSUE THREAD

**Issue by Admolly** [dlt-hub/dlt#567]
Hi There!

I'm just getting started with dlt.  I was wondering if there is any way to audit the code that your abstractions are generating.  Just curious what's actually going on behind-the-scenes when I run an ingestion pipeline.  Thanks for the help!

**Comment by adrianbr** [comment]
https://dlthub.com/docs/getting-started/build-a-data-pipeline#why-build-pipelines-with-dlt
dlt will "extract" data from your source via microbatching into "extracted" packages. If your source is generator, you will essentially microbatch it via the ram to hard disk. 

After extraction is finshed, the extracted pakcages are normalised in the same manner into load packages, for which a schema with loading hints can be generated.  This is then used to load the data to the destinaton.

To see how that happens you can inspect the load info and trace. The load_info object returned by the pipeline.run() method contains a wealth of information about the recently loaded data. About trace, read here: https://dlthub.com/docs/running-in-production/running#inspect-and-save-the-load-info-and-trace

Does this answer your question?
