### ISSUE TITLE
Windows subfolder creation

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/dlt#573]
as per the conversation from slack https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1692642594013989
there may be an issue creating subfolders

it could be the reason the previous user had an issue as well https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1692197105167629

**Comment by rudolfix** [comment]
@adrianbr thx or reporting. just checked the conversations. there's a lot of problems discussed there :) could you paste here relevant information or stack traces?

**Comment by sh-rp** [comment]
I have played around a bit with the windows folders and for me it works. I think I need a more concrete example where this error happens..

**Comment by rudolfix** [comment]
we were not able to reproduce the issue
