### ISSUE TITLE
use full pydantic typing when defining columns and allow the pydantic model to validate data during extraction

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#617]
**Background**
We have basic Pydantic support: we can define table schemas and load pydantic models. However we use just the basic Pydantic types and we do not use models for data validation.
Such validation was requested by community in #135 (data contracts). instead of extending our schema with all those enums, ranges and other validators let's just use Pydantic model in Python transform attached to a resource

**Requirements**
1. * [ ]  take look at types here https://docs.pydantic.dev/latest/usage/types/json/ and start recognize them when creating dlt schema from pydantic model. what for use we need is a JSON type - it was really missing. I also see Decimal there
2. * [ ] we must recognize Enums - ints and strings (and whatever else) when mapping to dlt schema
3. * [ ] let's use the model that got passed to validate data. it will be similar to our `incremental`. see below

**Validation Requirements**
1. * [ ] When pydantic model is passed to `apply_hints` we add a transform step (can be a add._map) where it is used to validate data
2. * [ ] we expose that step in DltResource - like we expose Incremental. we allow it to be set: if set to None we remove validation. otherwise it can be set to any other map function
3. * [ ] if validation fails we just raise. when #594 is merged we can recognize schema evolution settings and (1) drop the row or offending fields (2) allow for new/unknown fields to be present

@sh-rp @steinitzu WDYT? I think this is really easy to do and we'll get something way cooler than defining validators in JSON schema

**Comment by sh-rp** [comment]
I really like the idea. Would you want to pickle them and add them to the schema or would this always have to be in the code? For more advance validations, we could have a hook for every row.

**Comment by steinitzu** [comment]
This sounds great. It's no-brainer to use pydantic it if you want validation imo.

Are you thinking about just coercing enum to string or int in the schema? That's how I'm reading it atleast and I think that makes sense, could be complicated to support real enum on the destination level.

**Comment by rudolfix** [comment]
@sh-rp 
the validation should happen IMO in extract phase. so you can just keep model in memory and use it in validation transform

@steinitzu 
coercing. it is really bad idea to store enums in database (it is possible ie on postgres but IMO just a PITA)

**Comment by steinitzu** [comment]
Yeah makes sense. I used enum in postgres once, it was all fun until I had to add a value to it, wouldn't recommend it 😬
