### ISSUE TITLE
Bug when extracting to table named "state"

### ISSUE THREAD

**Issue by jkleinkauff** [dlt-hub/dlt#652]
### dlt version

0.3.17

### Describe the problem

When reading a csv file and trying to extract to a table named "state", dlt will thrown an error.

``` python
import dlt
import csv

def read_csv_file(file_path):
    with open(file_path, "r") as csvfile:
        reader = csv.reader(csvfile)
        header = next(reader)  # Read the header row

        for row in reader:
            yield dict(zip(header, row))

pipeline = dlt.pipeline(destination="filesystem", dataset_name="rawdata")

run_info = pipeline.run(
    read_csv_file("anycsv.csv"),
    table_name="state",
    write_disposition="replace",
)
```

> property 'state' of 'DltSource' object has no setter

If you change table_name to anything besides "state" the code will work.
The problem is not related to destination filesystem. Originally, I got when extracting to postgres as
well.

### Expected behavior

I expect the table to be extracted regardless it's name.

### Steps to reproduce

Run any pipeline using table_name = "state".

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

CSV

### dlt destination

Filesystem & buckets, Postgres

**Comment by burnash** [comment]
@jkleinkauff thank you again for reporting this.
