### ISSUE TITLE
Docs: Broken link on "Getting Started" page?

### ISSUE THREAD

**Issue by deeplook** [dlt-hub/dlt#678]
There appears to be a broken link in the [Getting Started](https://dlthub.com/docs/getting-started#quick-start) online page, trying to point to code snippets. I'm not quite sure where it should point to:

> "Looking for source code of all the snippets? You can find and run them [from this repository](https://github.com/dlt-hub/dlt/tree/devel/docs/snippets)."

https://github.com/dlt-hub/dlt/blob/57a207e4adf3243d379a371a7bf40da5792a65b0/docs/website/docs/getting-started.md?plain=1#L97

**Comment by ydv-ankit** [comment]
what link should be there

**Comment by burnash** [comment]
@deeplook thanks for reporting this. It's now fixed in #683
