### ISSUE TITLE
More supported date placeholders

### ISSUE THREAD

**Issue by dominikpeter** [dlt-hub/dlt#759]
### Feature description

We often follow a pattern like `/year/month/day/` to load data to our blob storage. This way the data is nicely organized by date. 

At the moment, `curr_date` is lacking this future, or I don't know how to use it this way. 

### Are you a dlt user?

I'd consider using dlt, but it's lacking a feature I need.

### Use case

Organize data by dates.

### Proposed solution

It would be nice to have more placeholders like `curr_year`, `curr_month`, `curr_day`, `curr_hour` and `curr_minute` or let the layout recognize date format pattern like for example `{table_name}/{%Y}/{%m}/{%d}`.

**Comment by burnash** [comment]
compared to other tools: https://github.com/dlt-hub/dlt/issues/555#issuecomment-1810176845

**Comment by Pipboyguy** [comment]
Subsumed by #930
