### ISSUE TITLE
Platform connection

### ISSUE THREAD

**Issue by sh-rp** [dlt-hub/dlt#776]
We need to send pipeline traces to the platform prototype. Eventually we want to use opentelemetry for this, but in the first iteration we will just send regular requests. 

For this the following needs to be done:

- [x] Introduce a new runtime config variable named platform_dsn, the user will place a url here which will be used to send data to the platform.
- [x] Allow multiple tracking modules in trace.py
- [x] Add a new tracking module that sends the pipeline run results on "end_trace_step" if a platform_dsn is present.
- [x] Optional: Do the sending on a separate thread (see segment.py for this) and implement exponential backoff on error.

Questions / Considerations
- [ ] Do we need threads and expontential backoff for this? The Python open telemetry client for python supports this and we will switch there eventually anyway.
- [ ] Where do we send additional info after a pipeline run? Such as the new schemas? Should we just send that in end_trace for now?

**Comment by rudolfix** [comment]
@sh-rp 
1. IMO it is way better to send through background pool. the code is already there. the post url can be part of the message (or we use some envelope on it)
2. no backoff or retry needed now. if you you use dlt requests, btw. they have backoff on certain codes already there. sending must end quickly...
3. what I'd do is to add a new flag to our `with_trace` decorator ie `send_sync` and do it in decorator if flag is set

Please also start sending traces in `sync_destination` (requires sync flag)

questions: does open telemetry support batching? that is IMO way more helpful than backoff etc. in terms of reliability
