### ISSUE TITLE
poetry install fails on Python 3.11: cannot install connectorx

### ISSUE THREAD

**Issue by jorritsandbrink** [dlt-hub/dlt#831]
### dlt version

dlt 0.4.1a2

### Describe the problem

`make dev` (which runs `poetry install`) fails when using Python 3.11:

![image](https://github.com/dlt-hub/dlt/assets/47451109/1d170eae-6069-48b1-a7f3-0529ed5cbc96)

I've experienced this issue when developing locally on Windows, but it also shows on Github runners on Ubuntu, MacOS, and Windows: https://github.com/dlt-hub/dlt/actions/runs/7231774021/job/19705316301

The issue seems to be that no wheel file is provided: https://stackoverflow.com/a/74450103

Perhaps this can be solved by upgrading `connectorx` to `0.3.2` (currently latest version), instead of `0.3.1`, which is used now. 

### Steps to reproduce

Using Python 3.11:

1. Clone `dlt` repo
2. Switch to `devel` branch
3. Run `make dev`

### Operating system

Linux, macOS, Windows

### Runtime environment

Local

### Python version

3.11

**Comment by rudolfix** [comment]
connectorx simply lacks Python 3.11 support in any of the stable 0.3.x versions. we use `connectorx` when building and linting documentation examples. my take would be to exclude `docs` poetry group from lint.yml. we have a separate workflow that lints docs examples

**Comment by jorritsandbrink** [comment]
@rudolfix

Did a quick test and it looks like `connectorx==0.3.2` does support Python 3.11:
![image](https://github.com/dlt-hub/dlt/assets/47451109/22afcdb2-20bb-44e8-ae22-d5e003faa5b9)

Do you suggest upgrading `connectorx` or excluding `docs` poetry group from `lint.yml`?
