### ISSUE TITLE
Normalize keys for google secrets lookup (or dissallow space in pipeline name)

### ISSUE THREAD

**Issue by sh-rp** [dlt-hub/dlt#880]
### dlt version

0.4.2

### Describe the problem

If the pipeline name has a space in it (eg. "chess_pipeline_ blah"), looking up secrets in google secrets produces an error such as:

```log
2024-01-08 12:50:39,563|[WARNING              ]|20924|4504413696|dlt|google_secrets.py|_look_vault:62|
Unable to read chess_pipeline_ blah-destination-staging_config :
The provided Secret Version ID
[projects/989930050503/secrets/chess_pipeline_ blah-destination-staging_config/versions/latest]
does not match the expected format [projects/*/secrets/*/versions/*][INVALID_ARGUMENT]
```

### Expected behavior

There should be no error

### Steps to reproduce

Connect to google secrets and run with a pipeline that has a space in the name.

### Operating system

macOS

### Runtime environment

Local

### Python version

3.10

**Comment by rudolfix** [comment]
hmmm. keys should be normalized!
```

class GoogleSecretsProvider(VaultTomlProvider):
    def __init__(
        self,
        credentials: GcpServiceAccountCredentials,
        only_secrets: bool = True,
        only_toml_fragments: bool = True,
    ) -> None:
        self.credentials = credentials
        super().__init__(only_secrets, only_toml_fragments)

    @staticmethod
    def get_key_name(key: str, *sections: str) -> str:
        return get_key_name(key, "-", *sections)
```
so `get_key_name` is simplistic and not trying to normalize the alphabet. for comparison: take a look at environ which always uses upper case
```
@staticmethod
    def get_key_name(key: str, *sections: str) -> str:
        return get_key_name(key, "__", *sections).upper()
```

**Comment by sultaniman** [comment]
@rudolfix @sh-rp I tried to reproduce the same issue with `0.4.2` and the latest `0.4.3a` for chess pipeline against big query and wasn't able to reproduce it.
