### ISSUE TITLE
Ability to define /configure target schema for staging tables and dlt internal tables.

### ISSUE THREAD

**Issue by sohail-ali** [dlt-hub/dlt#919]
## Requirements:
Allow to specify the name of the staging dataset in destination configuration.
1. * [x] The default setting should be the current name `%s_staging` where %s is schema name
2. * [x] also allow a string without placeholders (ie. `_dlt_staging` as discussed below)
3. * [x] currently both filesystem.py and sql_client.py create staging dataset name. this should happen in one place, preferably in the destination configuration itself.
4. * [x] write a test (duckdb is sufficient) where a string without placeholders is used and load data to a few different schemas, make sure that staging dataset for particular schema is
5. * [x] document in using dlt / destination

----------
### Feature description

Currently dlt internal tables are created in same schema where target table was created. If you have multiple target schemas than internal tables are created in all those schemas. I would be better to have an option to specify dedicated schema for internal tables and also for staging tables.

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

Currently dlt internal tables are created in same schema where target table was created. If you have multiple target schemas than internal tables are created in all those schemas. I would be better to have an option to specify dedicated schema for internal tables and also for staging tables.

### Proposed solution

Option to specify target schema for dlt internal and staging tables.  

Destination: snowflake

**Comment by rudolfix** [comment]
@sohail-ali a few questions:
1. staging dataset is kept in a separate schema (`<schema_name>_staging`) or are you referring to something else here
> I would be better to have an option to specify dedicated schema for internal tables **and also for staging tables.**

2. if there are multiple target schemas we indeed create internal schemas in all of them. assuming that we create them in a single schema: is it ok to have a internal table name prefixed with schema name so we can keep data separated or we need to add schema name to the table as a column?
3. are you by any chance using `use_single_dataset` set to False in the pipeline configuration?
4. I do not understand how this change would help you at the end. is this more aesthetic? or you have some data replication/backup problem?
sorry if I missed any details in our slack

**Comment by sohail-ali** [comment]
1. For staging dataset instead of having <schema_name>_staging. Can we configure single staging dataset for all the resources like _dlt_staging. Current approach will create multiple staging schemas in the database. This is more of an an aesthetic requirement rather than functional need. We like our target database / schema to look more like source database / schema. So  any internal tables or staging schemas created by dlt like them to be under one schema.

**Comment by rudolfix** [comment]
OK I get it, it looks to me that an additional configuration where staging dataset name can be defined (with the default to current behavior should be enough). just pls keep in mind that if you have table name conflict and you load to a single dataset, `dlt` will create a single union table of column from both.

**Comment by rudolfix** [comment]
@sohail-ali available in 0.5.1
