### ISSUE TITLE
Airflow helper: expose internal runner and introduce parallel execution of resources

### ISSUE THREAD

**Issue by rubenhelsloot** [dlt-hub/dlt#931]
## Requirements
1. allow airflow helper users to construct their own Dags but still to use internal runner with all the options (see example code at the very bottom)
2. introduce two new "decompose" types
- **parallel** will execute scc components in parallel, except the first component that must complete first (just in case)
- **parallel-isolated** will execute scc components in parallel. before execution pipeline will be forked under new name so state will be isolated
3. parallel options must be documented in docstring and docs

### additional requirement for `parallel`
We need to warn users if they modify the state of the resource in any of the tasks that are run in parallel. Please do the following:
when creating DAG enumerate all the resources in given component. if any of the resources has `incremental` property set, please log a warning like this
`The resource {resource.name} in task {task.name} is using incremental loading and may modify the state. Resources that modify the state should not run in parallel within the single pipeline as the state will not be correctly merged. Please use "serialize" or "parallel-isolated" modes instead`

First component may modify the state.

### **parallel-isolated** requirements
The goal of this decompose type is to run parallel several resources that modify the state. We achieve that by allocating a separate pipeline name (which will isolate the state) to each component. All such pipelines will write to the same dataset and work on the same schema,
1. * [ ] the overall DAG should be exactly  as in `parallel` mode, with a single starting task
2. * [ ] before creating task, the existing pipeline must be dropped `pipeline.drop()` - but we must be allowed to give it a separate name
3. * [ ] you must add a new argument to drop that will override the default pipeline name and pass it internally
4. * [ ] please add a test for the above alongside the regular drop test
5. * [ ] `drop` returns a clone of the original pipeline object. pass it to the task run

### dlt version

0.4.1

### Describe the problem

**Situation**
I have several Airflow dags that each select a subset of tables from SAP Hana to transfer using dlt. To do this, I'm using the generic SQL loader with a few minor tweaks. I define each subset as a dag using the `PipelineTasksGroup` class and split each subset into one task per table using `decompose`.

My problem is that on each heartbeat, Airflow evaluates the structure of all dags, which means it constructs the `dlt.source` object in every dag, and that means that it calls the SQLAlchemy constructor `Table()` on every named table. This actually connects to the Hana instance to fetch table metadata.

All this makes the dags very slow to load, and sometimes even throw timeout errors. It's also just considered [not good practice](https://docs.astronomer.io/learn/dag-best-practices#avoid-top-level-code-in-your-dag-file) to have expensive evaluations in that initial setup code.

**Workaround**
As a workaround, I can decompose and define the tasks myself, creating one `dlt.pipeline` for each task. However, that means I can't use all the nice Airflow hacks you defined in the `PipelineTasksGroup`...

```
def dlt_load_hana_dag_factory(config):
    @dag(
        dag_id=config.dag_id,
        schedule=config.schedule,
        start_date=datetime(2023, 10, 1),
        tags=["load", config.schedule or "one-time", *config.tags],
        default_args={
            "owner": "airflow",
            "retries": 0,
            "retry_exponential_backoff": True,
            # "task_concurrency": 1,
            **(config.default_args or {}),
        },
        catchup=False,
    )
    def load_hana_dag():
        postgres_credentials = PostgresHook().get_uri()
        hana_credentials = HanaHook().get_uri()

        start = EmptyOperator(task_id="start")
        end = EmptyOperator(task_id="end", trigger_rule="all_success")

        @task
        def load_hana_table(table: HanaTableSource):
            # Pipe dlt logging to the Airflow task logger
            ti = get_current_context()["ti"]
            dlt.common.logger.LOGGER = ti.log
            ti.log.info(
                f"Loading {table.schema}.{table.table} into {table.postgres_table_name}"
            )

            pipeline = dlt.pipeline(
                pipeline_name=config.dag_id,
                destination=postgres(credentials=postgres_credentials),
                dataset_name=config.dataset_name,
                progress=LogCollector(log_period=30, logger=ti.log),
            )
            pipeline.run(
                hana(credentials=hana_credentials, tables=[table]),
                table_name=table.postgres_table_name,
            )

        tasks = [
            load_hana_table.override(task_id=f"hana_{t.postgres_table_name}")(t)
            for t in config.hana_tables
        ]
        start >> tasks >> end

    return load_hana_dag()
```

**My question**
Given that I know the names of the tables for each source, do you know of a way to a pipeline that is lazily evaluated, while still using the `PipelineTasksGroup`?

Thanks for the amazing product!

### Steps to reproduce

Create a dag like the following and run `airflow dags report`. See that it takes a longer time (6s in my case) to parse the file.

```
from datetime import datetime

import dlt
from airflow.models.dag import dag
from dlt.helpers.airflow_helper import PipelineTasksGroup

from include.hana_tables.rse_tables import RSE_TABLES
from include.hooks.hana import HanaHook
from include.sources.hana import hana


@dag(
    schedule=None,
    start_date=datetime(2023, 10, 1),
    tags=["test"],
    default_args={
        "owner": "airflow",
        "retries": 0,
        "retry_exponential_backoff": True,
    },
    catchup=False,
)
def test_dag():
    tasks = PipelineTasksGroup(
        pipeline_name="test_dag",
    )

    pipeline = dlt.pipeline(
        pipeline_name="pipedrive", destination="postgres", dataset_name="raw"
    )
    hana_credentials = HanaHook().get_uri()
    source = hana(credentials=hana_credentials, tables=RSE_TABLES)

    tasks.add_run(
        pipeline,
        source,
        decompose="serialize",
        trigger_rule="all_done",
        retries=0,
    )


test_dag()
```

### Operating system

macOS

### Runtime environment

Local

### Python version

6.11

### dlt data source

SAP Hana, based on the official `sql_database` source

### dlt destination

Postgres

**Comment by rudolfix** [comment]
@rubenhelsloot thanks for this bug report! I see 3 ways we could fix this:
1. we can enhance the `decompose="none"` so it accepts lazily evaluated sources. the database will be reflected only when task is run. in that case you will not see a nice DAG just a single task in which all tables are evaluated. this fix is straightforward but probably not what you really want :)
2. if you know your tables in advance, you can use `sql_table` instead of `sql_database`. `sql_table` will still reflect database though. we could an option here to lazily reflect the table schema. that will require changes in the core library (which btw. we had planned already) and in the sql_database source
3. we can support your workaround better (which is quite nice btw.) there's already a stub in our airflow helper (`add_fun`) and the intention there was that the user can pass a function that will be evaluated at runtime, return pipeline instance and data and then will be executed by our runner. `add_fun` will return a task instance so you can manipulate them as you want

my take would be to do (3). honestly I'd prefer to do (2) but here the ETA is not clear. (3) could be most probably included in the next release (~2 weeks time)
does (3) look good to you?

**Comment by rudolfix** [comment]
and one question:
> My problem is that on each heartbeat, Airflow evaluates the structure of all dags,

so this happens all the time? if you are disconnected from the web app (not looking at the logs/dags) as well?

**Comment by rubenhelsloot** [comment]
The downside of writing my own workaround was that I couldn't use your knowledge of dlt on Airflow. For example, having the logging piped to Airflow's logging is very nice as I'm running it on AWS' Managed Airflow (MWAA) environment. Both options 2 and 3 seem like they would still allow me to piggyback on your expertise here!

So just to check, option 3 would be something like the following, right?

```
tasks = PipelineTasksGroup(pipeline_name="dlt_load_hana")
def get_data():
    pipeline = dlt.pipeline(
        pipeline_name="pipedrive", destination="postgres", dataset_name="raw"
    )
    hana_credentials = HanaHook().get_uri()
    source = hana(credentials=hana_credentials, tables=RSE_TABLES)

tasks.add_fun(get_data, decompose="serialize", trigger_rule="all_done", retries=0)
```

In that case, I think option 3 would definitely be useful. I might even be able to contribute to a PR if that is welcome!

> so this happens all the time? if you are disconnected from the web app (not looking at the logs/dags) as well?

The code is executed on every re-evaluation of the DagBag; by default this is every 30 seconds and it throws if evaluation takes more than 30s. Loading one DAG with the pattern takes 7s with the `PipelineTasksGroup` setup, so you quickly run into problems unless you increase that threshold.

Two more questions I had:

1. I saw that you set the `DLT_DATA_DIR` env variable to a unique string, but is this executed on DAG evaluation? If so, am I right that it would set the env variable every 30 seconds and could lead to data loss? Or that having two worker processes on the same node could cause issues where one sets the value to something different from the other?

2. In the current setup, the sources are run one after the other, but I would actually like them to be run in parallel. I could achieve this by just deleting the `upstream_task_ids` and `downstream_task_ids` like so.

```
  tis = tasks.add_run(
        pipeline,
        source,
        decompose="serialize",
        trigger_rule="all_done",
        retries=0,
    )
    
    for ti in tis:
        ti.downstream_task_ids = set()
        ti.upstream_task_ids = set()
```

Is there a reason to prefer having the tasks run in series? If not, would it be possible to make this configurable?

**Comment by rudolfix** [comment]
Option 3: It looks that we should simply expose our internal airflow runner for example:
```python
def dlt_load_hana_dag_factory(config):
    @dag(
        dag_id=config.dag_id,
        schedule=config.schedule,
        start_date=datetime(2023, 10, 1),
        tags=["load", config.schedule or "one-time", *config.tags],
        default_args={
            "owner": "airflow",
            "retries": 0,
            "retry_exponential_backoff": True,
            # "task_concurrency": 1,
            **(config.default_args or {}),
        },
        catchup=False,
    )
    def load_hana_dag():
        postgres_credentials = PostgresHook().get_uri()
        hana_credentials = HanaHook().get_uri()
    
        task_group = PipelineTasksGroup(pipeline_name="dlt_load_hana")
        with task_group:

            @task
            def load_hana_table(table: HanaTableSource):
                pipeline = dlt.pipeline(
                    pipeline_name=config.dag_id,
                    destination=postgres(credentials=postgres_credentials),
                    dataset_name=config.dataset_name
                )
                # expose internal runner
                task_group.pipeline_run(
                    pipeline,
                    hana(credentials=hana_credentials, tables=[table]),
                    table_name=table.postgres_table_name,
                )

            tasks = [
                load_hana_table.override(task_id=f"hana_{t.postgres_table_name}")(t)
                for t in config.hana_tables
            ]
            start = EmptyOperator(task_id="start")
            end = EmptyOperator(task_id="end", trigger_rule="all_success")
            
            start >> tasks >> end

    return load_hana_dag()

```

ad 1. Setting os.environ does not propagate new value to the shell, it just changes in-memory dictionary. There will be only one pipeline executing per worker process so changing it should not impact any other.

ad 2. it is trivial to add parallel execution (ie. we could add decompose = "parallel") if your resources do not create any pipeline state. this is the case in your workaround (sql_database does not use state as long as you do not set up incremental loading) - it can execute in parallel. you can read more here:
https://dlthub.com/docs/reference/performance#source-decomposition-for-serial-and-parallel-resource-execution
https://dlthub.com/docs/general-usage/state#syncing-state-with-destination

**Comment by rudolfix** [comment]
@rubenhelsloot in the meantime our `sql_database` can reflect table schema during execution. so when DAG is created no call to the database engine is made. this does not (yet) let you run tasks in parallel in our standard runner but the serialized option won't overload your database.

we are working at the parallel execution now
