### ISSUE TITLE
allow to define maximum nesting level per resource

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/dlt#945]
**Background**
We want our users to specify maximum nesting level on a resource. Nesting level is a property of relational json normalizer so I'm reluctant to add it to dlt.resource, on the other hand it would be very useful to do so.
Implementation may require a change in schema representation. currently relational normalizer has its own configuration fragment with it's own hints for tables. we may want to keep those together using `x-normalizer-` hint.

**Comment by nauxliu** [comment]
Is that possible to support specify a subset of fields to un-nesting?

**Comment by rudolfix** [comment]
@nauxliu yes, you can tell dlt which fields to unnest and which do not:
https://dlthub.com/docs/general-usage/resource#define-schema

here `tags` field will be loaded as JSON and not as child table

**Comment by rudolfix** [comment]
my take would be to use `x-normalize: - nesting-level` or similar hint on the table in the normalizer area and additionally interpret it in the `relational`. since we already have it in `dlt.source` I think I can tolerate it in dlt.resource :)
