### ISSUE TITLE
Delta table as file destination

### ISSUE THREAD

**Issue by johalnes** [dlt-hub/dlt#978]
### Feature description

The feature I like most with delta tables is the possibility to use it without need for cataloging etc. In my head this makes it similar to Parquet for the end user, but with the nice features for [updates](https://delta.io/blog/2023-10-22-delta-rs-python-v0.12.0/), appending etc. And these features maybe makes it more suitable for DLT? 

Would love to see it as a file destination alongside Parquet 🙂 

### Are you a dlt user?

Yes, I use it for fun.

### Use case

With Microsoft Fabric, all PowerBI users suddenly wants Delta Tables. To be able to use DLT with the structure it comes with, and upload it directly to Azure Storage as Delta, without the need to load parquets into delta tables as a separate process, would be really nice.

**Comment by rudolfix** [comment]
we move full merge support to another ticket. so this is now done!
