### ISSUE TITLE
Python 3.8-9: AttributeError in validate_dict() with TTableHintTemplate

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#999]
### dlt version

0.4.4

### Describe the problem

`dlt.common.validation.validate_dict()` fails when validating TypedDict with `dlt.extract.typing.TTableHintTemplate` in Python 3.8.17.

When running this script on Python 3.8.17
**UPD**: Same in 3.9.15.

```python
from typing import TypedDict
from dlt.common.validation import validate_dict
from dlt.extract.typing import TTableHintTemplate


class TTestRecord(TypedDict):
    name: TTableHintTemplate[str]


test_item = {"name": "test"}
validate_dict(TTestRecord, test_item, path=".")
```

I get:
```
Traceback (most recent call last):
  File "test_validation.py", line 11, in <module>
    validate_dict(TTestRecord, test_item, path=".")
  File "XXX/dlt/common/validation.py", line 171, in validate_dict
    verify_prop(pk, pv, allowed_props[pk])
  File "XXX/dlt/common/validation.py", line 89, in verify_prop
    verify_prop(pk, pv, ut)
  File "XXX/dlt/common/validation.py", line 164, in verify_prop
    f"In {path}: field {pk} has expected type {t.__name__} which lacks validator",
  File "XXX/.pyenv/versions/3.8.17/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

In Python 3.11.5 `validate_dict` does not raise.

### Expected behavior

Should not raise in Python 3.8 as well.

### Steps to reproduce

Run the above test script in Python 3.8.17.

### Operating system

macOS

### Runtime environment

Local

### Python version

3.8

**Comment by willi-mueller** [comment]
Thank you for reporting! It's also broken for me on Python 3.9.15.

**Comment by willi-mueller** [comment]
It works for me using Python 3.11.4

**Comment by rudolfix** [comment]
1. not all hints have name!
2. TTableHintTemplate[str] must validate both string and callable returning string
